adb shell mkdir /data/local/tmp/mnn-profiler
adb push libMNN.so /data/local/tmp/mnn-profiler
adb push libMNN_CL.so /data/local/tmp/mnn-profiler
adb push libMNN_Express.so /data/local/tmp/mnn-profiler
adb push libllm.so /data/local/tmp/mnn-profiler
adb push llm_demo /data/local/tmp/mnn-profiler
adb push profiler /data/local/tmp/mnn-profiler
adb push spec_eval /data/local/tmp/mnn-profiler
adb push eagle_benchmark  /data/local/tmp/mnn-profiler
adb push ${QNN_SDK_ROOT}/lib/aarch64-android/libQnnHtp.so /data/local/tmp/mnn-profiler
adb push ${QNN_SDK_ROOT}/lib/aarch64-android/libQnnHtpV${HEXAGON_ARCH}Stub.so /data/local/tmp/mnn-profiler
adb push ${QNN_SDK_ROOT}/lib/hexagon-v${HEXAGON_ARCH}/unsigned/libQnnHtpV${HEXAGON_ARCH}Skel.so /data/local/tmp/mnn-profiler
adb push ${QNN_SDK_ROOT}/lib/aarch64-android/libQnnHtpPrepare.so /data/local/tmp/mnn-profiler
adb push ${QNN_SDK_ROOT}/lib/aarch64-android/libQnnSystem.so /data/local/tmp/mnn-profiler
