#include "opencl_source_map.hpp" 
namespace MNN { 
#ifndef MNN_OPENCL_BUFFER_CLOSED
const char* attention_buf = 
"#ifdef MNN_SUPPORT_FP16\n"
"#pragma OPENCL EXTENSION cl_khr_fp16 : enable\n"
"#endif\n"
"#ifdef FA_SUBGROUP\n"
"#pragma OPENCL EXTENSION cl_khr_subgroups : enable\n"
"#endif\n"
"#define GLOBAL_SIZE_3_DIMS "" __private const int global_size_dim0,__private const int global_size_dim1,__private const int global_size_dim2,\n"
"#define DEAL_NON_UNIFORM_DIM3(input1, input2, input3) "" if (input1 >= global_size_dim0 || input2 >= global_size_dim1 || input3 >= global_size_dim2) { "" return; "" }\n"
"#define GLOBAL_SIZE_2_DIMS "" __private const int global_size_dim0,__private const int global_size_dim1,\n"
"#define DEAL_NON_UNIFORM_DIM2(input1, input2) "" if (input1 >= global_size_dim0 || input2 >= global_size_dim1) { "" return; "" }\n"
"#define DEAL_OUTER_SEQLEN_NOT_ALIGN(length) "" if(4 * sl + 3 >= length) {"" temp_3 = (FLOAT4)0;"" }"" if(4 * sl + 2 >= length) {"" temp_2 = (FLOAT4)0;"" }"" if(4 * sl + 1 >= length) {"" temp_1 = (FLOAT4)0;"" }\n"
"#define DEAL_INNER_HEADDIM_NOT_ALIGN(length) "" if(hd * 4 + 3 >= length) {"" temp_0.w = (FLOAT)0;"" temp_1.w = (FLOAT)0;"" temp_2.w = (FLOAT)0;"" temp_3.w = (FLOAT)0;"" }"" if(hd * 4 + 2 >= length) {"" temp_0.z = (FLOAT)0;"" temp_1.z = (FLOAT)0;"" temp_2.z = (FLOAT)0;"" temp_3.z = (FLOAT)0;"" }"" if(hd * 4 + 1 >= length) {"" temp_0.y = (FLOAT)0;"" temp_1.y = (FLOAT)0;"" temp_2.y = (FLOAT)0;"" temp_3.y = (FLOAT)0;"" }\n"
"__kernel void rearrange_qkv(GLOBAL_SIZE_3_DIMS\n"
" __global const FLOAT *input_q,//[batch,seqLenQ/4,headNum,headDim,seqLenQ_4]\n"
" __global const FLOAT *input_k,// [batch,seqLenKV/4,headNum/group,headDim,seqLenKV_4]\n"
" __global const FLOAT *input_v,// [batch,seqLenKV/4,headNum/group,headDim,seqLenKV_4]\n"
" __global FLOAT *output_q,// [batch*headNum,ROUND_UP(headDim,mTileHDK),ROUND_UP(seqLenQ,mTileQ)]\n"
" __global FLOAT *output_k,// [batch*headNum/group,ROUND_UP(headDim,mTileHDK),ROUND_UP(seqLenKV,mTileKV)]\n"
" __global FLOAT *output_v,// [batch*headNum/group,ROUND_UP(seqLenKV,mTileKV),ROUND_UP(headDim,mTileHDN)]\n"
" #ifdef SAVE_KV\n"
" __global FLOAT *past_k,// [batch,headNum/group,headDim,seqLenKV_4]\n"
" __global FLOAT *past_v,// [batch,headNum/group,seqLenKV_4,headDim]\n"
" #endif\n"
" __private const int4 tile,// [mTileQ,mTileKV,mTileHDK,mTileHDN]\n"
" __private const int4 shape,// [seqLenQ,seqLenKV,headNum,headDim]\n"
" __private const int4 param,// [group,batch,max_len,past_len]\n"
" __private const int maxLenKV\n"
") {\n"
" const int sl=get_global_id(0); // seqLen/4 : max(seqLenPackQ/4,seqLenPackKV/4)\n"
" const int hd=get_global_id(1); // headDim/4 : max(headDimPackQK/4,headDimPackV/4)\n"
" const int z=get_global_id(2); // batch*headNum\n"
" DEAL_NON_UNIFORM_DIM3(sl,hd,z);\n"
" \n"
" const int seqLenQ=shape.x;\n"
" const int seqLenKV=shape.y;\n"
" const int headNum=shape.z;\n"
" const int headDim=shape.w;\n"
" const int group=param.x;\n"
" const int batch=param.y;\n"
" const int b=z % batch;\n"
" const int hn=z/batch;\n"
" \n"
" const int seqLenQ_4=(seqLenQ+3)/4;\n"
" //const int in_offset_q=(((b*seqLenQ_4+sl)*headNum+hn)*headDim+4*hd)*4;\n"
" const int in_offset_q=(((b*seqLenQ+sl*4)*headNum+hn)*headDim+4*hd);\n"
" const int seqLenPackQ=((seqLenQ+tile.x-1)/tile.x)*tile.x;\n"
" const int headDimPackQK=((headDim+tile.z-1)/tile.z)*tile.z;\n"
" const int out_offset_q=(((b*headNum+hn)*headDimPackQK+hd*4)*seqLenPackQ+sl*4);\n"
" \n"
" if(sl*4<seqLenPackQ && hd*4<headDimPackQK) {\n"
" if(sl*4 >= seqLenQ || hd*4 >= headDim) {\n"
" vstore4((FLOAT4)0,0,output_q+out_offset_q);\n"
" vstore4((FLOAT4)0,0,output_q+out_offset_q+seqLenPackQ);\n"
" vstore4((FLOAT4)0,0,output_q+out_offset_q+2*seqLenPackQ);\n"
" vstore4((FLOAT4)0,0,output_q+out_offset_q+3*seqLenPackQ);\n"
" } else {\n"
" FLOAT4 temp_0=vload4(0,input_q+in_offset_q);\n"
" FLOAT4 temp_1=(sl*4+1 >= seqLenQ) ? (FLOAT4)0 : vload4(0,input_q+in_offset_q+headNum*headDim);\n"
" FLOAT4 temp_2=(sl*4+2 >= seqLenQ) ? (FLOAT4)0 : vload4(0,input_q+in_offset_q+2*headNum*headDim);\n"
" FLOAT4 temp_3=(sl*4+3 >= seqLenQ) ? (FLOAT4)0 : vload4(0,input_q+in_offset_q+3*headNum*headDim);\n"
" #ifdef HEADDIM_LEAVE\n"
" DEAL_INNER_HEADDIM_NOT_ALIGN(headDim)\n"
" #endif\n"
" #ifdef SEQLEN_LEAVE\n"
" DEAL_OUTER_SEQLEN_NOT_ALIGN(seqLenQ)\n"
" #endif\n"
" vstore4((FLOAT4)(temp_0.s0,temp_1.s0,temp_2.s0,temp_3.s0),0,output_q+out_offset_q);\n"
" vstore4((FLOAT4)(temp_0.s1,temp_1.s1,temp_2.s1,temp_3.s1),0,output_q+out_offset_q+seqLenPackQ);\n"
" vstore4((FLOAT4)(temp_0.s2,temp_1.s2,temp_2.s2,temp_3.s2),0,output_q+out_offset_q+2*seqLenPackQ);\n"
" vstore4((FLOAT4)(temp_0.s3,temp_1.s3,temp_2.s3,temp_3.s3),0,output_q+out_offset_q+3*seqLenPackQ);\n"
" }\n"
" }\n"
" \n"
" if(hn >= headNum/group) {\n"
" return;\n"
" }\n"
" \n"
" const int seqLenPackKV=((seqLenKV+tile.y-1)/tile.y)*tile.y;\n"
" const int headDimPackV=((headDim+tile.w-1)/tile.w)*tile.w;\n"
" const int seqLenKV_4=(seqLenKV+3)/4;\n"
" const int in_offset_kv=(((b*seqLenKV+sl*4)*headNum/group+hn)*headDim+4*hd);\n"
" const int past_offset_k=(((b*headNum/group+hn)*headDim+hd*4)*maxLenKV+sl*4);\n"
" const int past_offset_v=(((b*headNum/group+hn)*maxLenKV+sl*4)*headDim+4*hd);\n"
" if(sl*4<seqLenPackKV && hd*4<headDimPackQK) {\n"
" const int out_offset_k=(((b*headNum/group+hn)*headDimPackQK+hd*4)*seqLenPackKV+sl*4);\n"
" if(sl*4 >= seqLenKV || hd*4 >= headDim) {\n"
" vstore4((FLOAT4)0,0,output_k+out_offset_k);\n"
" vstore4((FLOAT4)0,0,output_k+out_offset_k+seqLenPackKV);\n"
" vstore4((FLOAT4)0,0,output_k+out_offset_k+2*seqLenPackKV);\n"
" vstore4((FLOAT4)0,0,output_k+out_offset_k+3*seqLenPackKV);\n"
" } else {\n"
" FLOAT4 temp_0=vload4(0,input_k+in_offset_kv);\n"
" FLOAT4 temp_1=(sl*4+1 >= seqLenKV) ? (FLOAT4)0 : vload4(0,input_k+in_offset_kv+headNum*headDim/group);\n"
" FLOAT4 temp_2=(sl*4+2 >= seqLenKV) ? (FLOAT4)0 : vload4(0,input_k+in_offset_kv+2*headNum*headDim/group);\n"
" FLOAT4 temp_3=(sl*4+3 >= seqLenKV) ? (FLOAT4)0 : vload4(0,input_k+in_offset_kv+3*headNum*headDim/group);\n"
" #ifdef HEADDIM_LEAVE\n"
" DEAL_INNER_HEADDIM_NOT_ALIGN(headDim)\n"
" #endif\n"
" #ifdef SEQLEN_LEAVE\n"
" DEAL_OUTER_SEQLEN_NOT_ALIGN(seqLenKV)\n"
" #endif\n"
" FLOAT4 key0=(FLOAT4)(temp_0.s0,temp_1.s0,temp_2.s0,temp_3.s0);\n"
" FLOAT4 key1=(FLOAT4)(temp_0.s1,temp_1.s1,temp_2.s1,temp_3.s1);\n"
" FLOAT4 key2=(FLOAT4)(temp_0.s2,temp_1.s2,temp_2.s2,temp_3.s2);\n"
" FLOAT4 key3=(FLOAT4)(temp_0.s3,temp_1.s3,temp_2.s3,temp_3.s3);\n"
" vstore4(key0,0,output_k+out_offset_k);\n"
" vstore4(key1,0,output_k+out_offset_k+seqLenPackKV);\n"
" vstore4(key2,0,output_k+out_offset_k+2*seqLenPackKV);\n"
" vstore4(key3,0,output_k+out_offset_k+3*seqLenPackKV);\n"
" \n"
" // pastK\n"
" #ifdef SAVE_KV\n"
" vstore4(key0,0,past_k+past_offset_k);\n"
" vstore4(key1,0,past_k+past_offset_k+maxLenKV);\n"
" vstore4(key2,0,past_k+past_offset_k+2*maxLenKV);\n"
" vstore4(key3,0,past_k+past_offset_k+3*maxLenKV);\n"
" #endif\n"
" }\n"
" \n"
" }\n"
" \n"
" if(sl*4<seqLenPackKV && hd*4<headDimPackV) {\n"
" const int out_offset_v=(((b*headNum/group+hn)*seqLenPackKV+sl*4)*headDimPackV+hd*4);\n"
" if(sl*4 >= seqLenKV || hd*4 >= headDim) {\n"
" vstore4((FLOAT4)0,0,output_v+out_offset_v);\n"
" vstore4((FLOAT4)0,0,output_v+out_offset_v+headDimPackV);\n"
" vstore4((FLOAT4)0,0,output_v+out_offset_v+2*headDimPackV);\n"
" vstore4((FLOAT4)0,0,output_v+out_offset_v+3*headDimPackV);\n"
" } else {\n"
" FLOAT4 temp_0=vload4(0,input_v+in_offset_kv);\n"
" FLOAT4 temp_1=(sl*4+1 >= seqLenKV) ? (FLOAT4)0 : vload4(0,input_v+in_offset_kv+headNum*headDim/group);\n"
" FLOAT4 temp_2=(sl*4+2 >= seqLenKV) ? (FLOAT4)0 : vload4(0,input_v+in_offset_kv+2*headNum*headDim/group);\n"
" FLOAT4 temp_3=(sl*4+3 >= seqLenKV) ? (FLOAT4)0 : vload4(0,input_v+in_offset_kv+3*headNum*headDim/group);\n"
" #ifdef HEADDIM_LEAVE\n"
" DEAL_INNER_HEADDIM_NOT_ALIGN(headDim)\n"
" #endif\n"
" #ifdef SEQLEN_LEAVE\n"
" DEAL_OUTER_SEQLEN_NOT_ALIGN(seqLenKV)\n"
" #endif\n"
" vstore4(temp_0,0,output_v+out_offset_v);\n"
" vstore4(temp_1,0,output_v+out_offset_v+headDimPackV);\n"
" vstore4(temp_2,0,output_v+out_offset_v+2*headDimPackV);\n"
" vstore4(temp_3,0,output_v+out_offset_v+3*headDimPackV);\n"
" \n"
" // pastV\n"
" #ifdef SAVE_KV\n"
" vstore4(temp_0,0,past_v+past_offset_v);\n"
" vstore4(temp_1,0,past_v+past_offset_v+headDim);\n"
" vstore4(temp_2,0,past_v+past_offset_v+2*headDim);\n"
" vstore4(temp_3,0,past_v+past_offset_v+3*headDim);\n"
" #endif\n"
" }\n"
" \n"
" }\n"
"}\n"
"#ifndef MASK_DTYPE\n"
"#define MASK_DTYPE FLOAT\n"
"#define MASK_DTYPE4 FLOAT4\n"
"#endif\n"
"__kernel void rearrange_mask(GLOBAL_SIZE_3_DIMS\n"
" __global const MASK_DTYPE *input_mask,// [batch,1,seqLenQ,seqLenKV,4]\n"
" __global MASK_DTYPE *output_mask,// [batch,ROUND_UP(seqLenQ,mTileQ),ROUND_UP(seqLenKV,mTileKV)]\n"
" const int4 shape // [seqLenQ,seqLenKV,mTileQ,mTileKV]\n"
") {\n"
" const int sl=get_global_id(0); // seqLen_4\n"
" const int sl_kv=get_global_id(1); // seqLenKV_4\n"
" const int b=get_global_id(2); // Batch\n"
" DEAL_NON_UNIFORM_DIM3(sl,sl_kv,b);\n"
" \n"
" const int seq_len_pack=((shape.x+shape.z-1)/shape.z)*shape.z;\n"
" const int seq_len_kv_pack=((shape.y+shape.w-1)/shape.w)*shape.w;\n"
" int in_offset=((b*shape.x+sl*4)*shape.y+sl_kv*4);\n"
" int out_offset=(b*seq_len_pack+sl*4)*seq_len_kv_pack+sl_kv*4;\n"
" if(sl*4 >= shape.x || sl_kv*4 >= shape.y) {\n"
" vstore4((MASK_DTYPE4)0,0,output_mask+out_offset);\n"
" vstore4((MASK_DTYPE4)0,0,output_mask+out_offset+seq_len_kv_pack);\n"
" vstore4((MASK_DTYPE4)0,0,output_mask+out_offset+seq_len_kv_pack*2);\n"
" vstore4((MASK_DTYPE4)0,0,output_mask+out_offset+seq_len_kv_pack*3);\n"
" } else {\n"
" int y_down_align4=(shape.y/4*4);\n"
" MASK_DTYPE4 temp_0,temp_1,temp_2,temp_3;\n"
" \n"
" if(sl_kv*4<y_down_align4) {\n"
" temp_0=vload4(0,input_mask+in_offset);\n"
" temp_1=(sl*4+1 >= shape.x) ? (MASK_DTYPE4)0 : vload4(0,input_mask+in_offset+shape.y);\n"
" temp_2=(sl*4+2 >= shape.x) ? (MASK_DTYPE4)0 : vload4(0,input_mask+in_offset+shape.y*2);\n"
" temp_3=(sl*4+3 >= shape.x) ? (MASK_DTYPE4)0 : vload4(0,input_mask+in_offset+shape.y*3);\n"
" } else if(sl_kv*4+1 == shape.y){\n"
" temp_0=(MASK_DTYPE4)(input_mask[in_offset],0,0,0);\n"
" temp_1=(sl*4+1 >= shape.x) ? (MASK_DTYPE4)0 : (MASK_DTYPE4)(input_mask[in_offset+shape.y],0,0,0);//vload4(0,input_mask+in_offset+shape.y);\n"
" temp_2=(sl*4+2 >= shape.x) ? (MASK_DTYPE4)0 : (MASK_DTYPE4)(input_mask[in_offset+shape.y*2],0,0,0);//vload4(0,input_mask+in_offset+shape.y*2);\n"
" temp_3=(sl*4+3 >= shape.x) ? (MASK_DTYPE4)0 : (MASK_DTYPE4)(input_mask[in_offset+shape.y*3],0,0,0);//vload4(0,input_mask+in_offset+shape.y*3);\n"
" } else if(sl_kv*4+2 == shape.y){\n"
" temp_0=(MASK_DTYPE4)(input_mask[in_offset],input_mask[in_offset+1],0,0);\n"
" temp_1=(sl*4+1 >= shape.x) ? (MASK_DTYPE4)0 : (FLOAT4)(input_mask[in_offset+shape.y],input_mask[in_offset+shape.y+1],0,0);//vload4(0,input_mask+in_offset+shape.y);\n"
" temp_2=(sl*4+2 >= shape.x) ? (MASK_DTYPE4)0 : (MASK_DTYPE4)(input_mask[in_offset+shape.y*2],input_mask[in_offset+shape.y*2+1],0,0);//vload4(0,input_mask+in_offset+shape.y*2);\n"
" temp_3=(sl*4+3 >= shape.x) ? (MASK_DTYPE4)0 : (MASK_DTYPE4)(input_mask[in_offset+shape.y*3],input_mask[in_offset+shape.y*3+1],0,0);//vload4(0,input_mask+in_offset+shape.y*3);\n"
" } else if(sl_kv*4+3 == shape.y){\n"
" temp_0=(MASK_DTYPE4)(input_mask[in_offset],input_mask[in_offset+1],input_mask[in_offset+2],0);\n"
" temp_1=(sl*4+1 >= shape.x) ? (MASK_DTYPE4)0 : (MASK_DTYPE4)(input_mask[in_offset+shape.y],input_mask[in_offset+shape.y+1],input_mask[in_offset+shape.y+2],0);//vload4(0,input_mask+in_offset+shape.y);\n"
" temp_2=(sl*4+2 >= shape.x) ? (MASK_DTYPE4)0 : (MASK_DTYPE4)(input_mask[in_offset+shape.y*2],input_mask[in_offset+shape.y*2+1],input_mask[in_offset+shape.y*2+2],0);//vload4(0,input_mask+in_offset+shape.y*2);\n"
" temp_3=(sl*4+3 >= shape.x) ? (MASK_DTYPE4)0 : (MASK_DTYPE4)(input_mask[in_offset+shape.y*3],input_mask[in_offset+shape.y*3+1],input_mask[in_offset+shape.y*3+2],0);//vload4(0,input_mask+in_offset+shape.y*3);\n"
" }\n"
" vstore4(temp_0,0,output_mask+out_offset);\n"
" vstore4(temp_1,0,output_mask+out_offset+seq_len_kv_pack);\n"
" vstore4(temp_2,0,output_mask+out_offset+2*seq_len_kv_pack);\n"
" vstore4(temp_3,0,output_mask+out_offset+3*seq_len_kv_pack);\n"
" }\n"
"}\n"
"__kernel void qkv_transpose_output(GLOBAL_SIZE_3_DIMS\n"
" __global const FLOAT *input,// [Batch*mNumHead,ROUND_UP(mHeadDim,mTileHDN),ROUND_UP(seqLen,mTileQ)]\n"
" __global FLOAT *output,// [Batch,seqLen/4,mNumHead， mHeadDim,4]\n"
" __private const int tile_q,\n"
" __private const int tile_hdn,\n"
" __private const int seq_len,\n"
" __private const int head_num,\n"
" __private const int head_dim\n"
") {\n"
" \n"
" const int sl=get_global_id(0); // seqLen_4\n"
" const int hd=get_global_id(1); // mHeadDim_4\n"
" const int z=get_global_id(2); // Batch*mNumHead\n"
" DEAL_NON_UNIFORM_DIM3(sl,hd,z);\n"
" \n"
" const int b=z/head_num;\n"
" const int hn=z % head_num;\n"
" \n"
" const int seq_len_pack=((seq_len+tile_q-1)/tile_q)*tile_q;\n"
" const int head_dim_pack=((head_dim+tile_hdn-1)/tile_hdn)*tile_hdn;\n"
" \n"
" const int offset_inp=((b*head_num+hn)*head_dim_pack+4*hd)*seq_len_pack+4*sl;\n"
" \n"
" const int offset_out=(((b*seq_len+sl*4)*head_num+hn)*head_dim+4*hd);\n"
" \n"
" // Q\n"
" FLOAT4 temp_0=vload4(0,input+offset_inp);\n"
" FLOAT4 temp_1=vload4(0,input+offset_inp+seq_len_pack);\n"
" FLOAT4 temp_2=vload4(0,input+offset_inp+2*seq_len_pack);\n"
" FLOAT4 temp_3=vload4(0,input+offset_inp+3*seq_len_pack);\n"
" \n"
" vstore4((FLOAT4)(temp_0.s0,temp_1.s0,temp_2.s0,temp_3.s0),0,output+offset_out);\n"
" if(4*sl+1 >= seq_len) return;\n"
" vstore4((FLOAT4)(temp_0.s1,temp_1.s1,temp_2.s1,temp_3.s1),0,output+offset_out+head_num*head_dim);\n"
" if(4*sl+2 >= seq_len) return;\n"
" vstore4((FLOAT4)(temp_0.s2,temp_1.s2,temp_2.s2,temp_3.s2),0,output+offset_out+2*head_num*head_dim);\n"
" if(4*sl+3 >= seq_len) return;\n"
" vstore4((FLOAT4)(temp_0.s3,temp_1.s3,temp_2.s3,temp_3.s3),0,output+offset_out+3*head_num*head_dim);\n"
"}\n"
"#ifndef NUMHEAD_GROUP_SIZE\n"
"#define NUMHEAD_GROUP_SIZE 1\n"
"#endif\n"
"__kernel void rearrange_q(GLOBAL_SIZE_3_DIMS\n"
" __global const FLOAT *query,// [batch query_seq_len head_num head_dim]\n"
" __global FLOAT *query_tmp,// [batch head_num head_dim_4 query_seq_len_4]\n"
" __private const int seq_len,\n"
" __private const int head_dim,\n"
" __private const int head_num) {\n"
" /*\n"
" the kernel assume head_dim is multiple of 4.\n"
" */\n"
" const int x=get_global_id(0); // query_seq_len/4\n"
" const int y=get_global_id(1); // head_dim/4\n"
" int z=get_global_id(2);\n"
" DEAL_NON_UNIFORM_DIM3(x,y,z);\n"
" \n"
" const int b=z/head_num;// batch\n"
" z=z % head_num;// head_num\n"
" \n"
" const int x4=x << 2;\n"
" const int y4=y << 2;\n"
" const int seq_len4=(seq_len+3)/4*4;;\n"
" const int stride=head_num*head_dim;\n"
" int query_offset=((b*seq_len+x4)*head_num+z)*head_dim+y4;\n"
" FLOAT4 query_vec0=vload4(0,query+query_offset); query_offset += stride;\n"
" FLOAT4 query_vec1=(x4+1 >= seq_len) ? (FLOAT4)0 : vload4(0,query+query_offset); query_offset += stride;\n"
" FLOAT4 query_vec2=(x4+2 >= seq_len) ? (FLOAT4)0 : vload4(0,query+query_offset); query_offset += stride;\n"
" FLOAT4 query_vec3=(x4+3 >= seq_len) ? (FLOAT4)0 : vload4(0,query+query_offset);\n"
" \n"
" const int queryout_offset=((b*head_num+z)*head_dim+y4)*seq_len4+x4;\n"
" vstore4((FLOAT4)(query_vec0.s0,query_vec1.s0,query_vec2.s0,query_vec3.s0),0,query_tmp+queryout_offset);\n"
" vstore4((FLOAT4)(query_vec0.s1,query_vec1.s1,query_vec2.s1,query_vec3.s1),0,query_tmp+queryout_offset+seq_len4);\n"
" vstore4((FLOAT4)(query_vec0.s2,query_vec1.s2,query_vec2.s2,query_vec3.s2),0,query_tmp+queryout_offset+seq_len4+seq_len4);\n"
" vstore4((FLOAT4)(query_vec0.s3,query_vec1.s3,query_vec2.s3,query_vec3.s3),0,query_tmp+queryout_offset+seq_len4+seq_len4+seq_len4);\n"
"}\n"
"__kernel void rearrange_q_packed(GLOBAL_SIZE_3_DIMS\n"
" __global const FLOAT *query,// [sum_seq_len,head_num,head_dim]\n"
" __global FLOAT *query_tmp,// packed by request: [head_num,head_dim,seq_len4]\n"
" __global const int *meta0,// [ioOffsetTokens,seqLen,pastLen,maxLen]\n"
" __global const int *meta1,// [qBaseElems,qkBaseElems,keyBaseElems,valueBaseElems]\n"
" __private const int head_dim,\n"
" __private const int head_num) {\n"
" const int x=get_global_id(0); // query_seq_len/4\n"
" const int y=get_global_id(1); // head_dim/4\n"
" const int z=get_global_id(2); // req_count*head_num\n"
" DEAL_NON_UNIFORM_DIM3(x,y,z);\n"
" const int req=z/head_num;\n"
" const int hn=z % head_num;\n"
" const int seq_len=meta0[req*4+1];\n"
" const int seq_len4=(seq_len+3)/4*4;\n"
" const int io_offset=meta0[req*4+0];\n"
" const int q_base=meta1[req*4+0];\n"
" const int x4=x << 2;\n"
" if (x4 >= seq_len) {\n"
" return;\n"
" }\n"
" const int y4=y << 2;\n"
" const int stride=head_num*head_dim;\n"
" int query_offset=((io_offset+x4)*head_num+hn)*head_dim+y4;\n"
" FLOAT4 query_vec0=vload4(0,query+query_offset); query_offset += stride;\n"
" FLOAT4 query_vec1=(x4+1 >= seq_len) ? (FLOAT4)0 : vload4(0,query+query_offset); query_offset += stride;\n"
" FLOAT4 query_vec2=(x4+2 >= seq_len) ? (FLOAT4)0 : vload4(0,query+query_offset); query_offset += stride;\n"
" FLOAT4 query_vec3=(x4+3 >= seq_len) ? (FLOAT4)0 : vload4(0,query+query_offset);\n"
" const int queryout_offset=q_base+((hn*head_dim+y4)*seq_len4+x4);\n"
" vstore4((FLOAT4)(query_vec0.s0,query_vec1.s0,query_vec2.s0,query_vec3.s0),0,query_tmp+queryout_offset);\n"
" vstore4((FLOAT4)(query_vec0.s1,query_vec1.s1,query_vec2.s1,query_vec3.s1),0,query_tmp+queryout_offset+seq_len4);\n"
" vstore4((FLOAT4)(query_vec0.s2,query_vec1.s2,query_vec2.s2,query_vec3.s2),0,query_tmp+queryout_offset+seq_len4+seq_len4);\n"
" vstore4((FLOAT4)(query_vec0.s3,query_vec1.s3,query_vec2.s3,query_vec3.s3),0,query_tmp+queryout_offset+seq_len4+seq_len4+seq_len4);\n"
"}\n"
"__kernel void rearrange_k(GLOBAL_SIZE_3_DIMS\n"
" __global const FLOAT *key,// [batch key_seq_len kv_head_num head_dim]\n"
" __global FLOAT *past_key,// [batch kv_head_num head_dim max_length]\n"
" __private const int past_len,// prefill=0,decode=past_key len\n"
" __private const int max_len,\n"
" __private const int seq_len,\n"
" __private const int kv_head_num,\n"
" __private const int head_num,\n"
" __private const int head_dim) {\n"
" \n"
" const int x=get_global_id(0); // seq_len decode=1\n"
" const int y=get_global_id(1); // head_dim\n"
" int z=get_global_id(2); //\n"
" DEAL_NON_UNIFORM_DIM3(x,y,z);\n"
" \n"
" const int b=z/kv_head_num;\n"
" z=z % kv_head_num;\n"
" const int y4=y << 2;\n"
" \n"
"#ifdef OPENCL_PREFILL_ATTENTION\n"
" const int x4=x << 2;\n"
" const int stride=kv_head_num*head_dim;\n"
" int key_offset=((b*seq_len+x4)*kv_head_num+z)*head_dim+y4;\n"
" FLOAT4 key_vec0=vload4(0,key+key_offset); key_offset += stride;\n"
" FLOAT4 key_vec1=(x4+1 >= seq_len) ? (FLOAT4)0 : vload4(0,key+key_offset); key_offset += stride;\n"
" FLOAT4 key_vec2=(x4+2 >= seq_len) ? (FLOAT4)0 : vload4(0,key+key_offset); key_offset += stride;\n"
" FLOAT4 key_vec3=(x4+3 >= seq_len) ? (FLOAT4)0 : vload4(0,key+key_offset);\n"
" const int output_offset=((b*kv_head_num+z)*head_dim+y4)*max_len+past_len+x4;\n"
" vstore4((FLOAT4)(key_vec0.s0,key_vec1.s0,key_vec2.s0,key_vec3.s0),0,past_key+output_offset);\n"
" vstore4((FLOAT4)(key_vec0.s1,key_vec1.s1,key_vec2.s1,key_vec3.s1),0,past_key+output_offset+max_len);\n"
" vstore4((FLOAT4)(key_vec0.s2,key_vec1.s2,key_vec2.s2,key_vec3.s2),0,past_key+output_offset+max_len+max_len);\n"
" vstore4((FLOAT4)(key_vec0.s3,key_vec1.s3,key_vec2.s3,key_vec3.s3),0,past_key+output_offset+max_len+max_len+max_len);\n"
"#else\n"
" FLOAT4 key_vec=vload4(0,key+(b*kv_head_num+z)*head_dim+y4);\n"
" const int output_offset=((b*kv_head_num+z)*head_dim+y4)*max_len+past_len;\n"
" past_key[output_offset]=key_vec.s0;\n"
" past_key[output_offset+max_len]=key_vec.s1;\n"
" past_key[output_offset+max_len+max_len]=key_vec.s2;\n"
" past_key[output_offset+max_len+max_len+max_len]=key_vec.s3;\n"
"#endif\n"
"}\n"
"__kernel void rearrange_k_packed(GLOBAL_SIZE_3_DIMS\n"
" __global const FLOAT *key,// [sum_seq_len,kv_head_num,head_dim]\n"
" __global FLOAT *past_key,// packed by request: [kv_head_num,head_dim,max_len]\n"
" __global const int *meta0,// [ioOffsetTokens,seqLen,pastLen,maxLen]\n"
" __global const int *meta1,// [qBaseElems,qkBaseElems,keyBaseElems,valueBaseElems]\n"
" __private const int kv_head_num,\n"
" __private const int head_num,\n"
" __private const int head_dim) {\n"
" const int x=get_global_id(0); // seq_len/4\n"
" const int y=get_global_id(1); // head_dim/4\n"
" const int z=get_global_id(2); // req_count*kv_head_num\n"
" DEAL_NON_UNIFORM_DIM3(x,y,z);\n"
" const int req=z/kv_head_num;\n"
" const int hn=z % kv_head_num;\n"
" const int seq_len=meta0[req*4+1];\n"
" const int past_len=meta0[req*4+2];\n"
" const int max_len=meta0[req*4+3];\n"
" const int io_offset=meta0[req*4+0];\n"
" const int key_base=meta1[req*4+2];\n"
" const int x4=x << 2;\n"
" if (x4 >= seq_len) {\n"
" return;\n"
" }\n"
" const int y4=y << 2;\n"
" const int stride=kv_head_num*head_dim;\n"
" int key_offset=((io_offset+x4)*kv_head_num+hn)*head_dim+y4;\n"
" FLOAT4 key_vec0=vload4(0,key+key_offset); key_offset += stride;\n"
" FLOAT4 key_vec1=(x4+1 >= seq_len) ? (FLOAT4)0 : vload4(0,key+key_offset); key_offset += stride;\n"
" FLOAT4 key_vec2=(x4+2 >= seq_len) ? (FLOAT4)0 : vload4(0,key+key_offset); key_offset += stride;\n"
" FLOAT4 key_vec3=(x4+3 >= seq_len) ? (FLOAT4)0 : vload4(0,key+key_offset);\n"
" const int output_offset=key_base+((hn*head_dim+y4)*max_len+past_len+x4);\n"
" if (past_len+x4<max_len) {\n"
" past_key[output_offset]=key_vec0.s0;\n"
" past_key[output_offset+max_len]=key_vec0.s1;\n"
" past_key[output_offset+max_len+max_len]=key_vec0.s2;\n"
" past_key[output_offset+max_len+max_len+max_len]=key_vec0.s3;\n"
" }\n"
" if (x4+1<seq_len && past_len+x4+1<max_len) {\n"
" past_key[output_offset+1]=key_vec1.s0;\n"
" past_key[output_offset+max_len+1]=key_vec1.s1;\n"
" past_key[output_offset+max_len+max_len+1]=key_vec1.s2;\n"
" past_key[output_offset+max_len+max_len+max_len+1]=key_vec1.s3;\n"
" }\n"
" if (x4+2<seq_len && past_len+x4+2<max_len) {\n"
" past_key[output_offset+2]=key_vec2.s0;\n"
" past_key[output_offset+max_len+2]=key_vec2.s1;\n"
" past_key[output_offset+max_len+max_len+2]=key_vec2.s2;\n"
" past_key[output_offset+max_len+max_len+max_len+2]=key_vec2.s3;\n"
" }\n"
" if (x4+3<seq_len && past_len+x4+3<max_len) {\n"
" past_key[output_offset+3]=key_vec3.s0;\n"
" past_key[output_offset+max_len+3]=key_vec3.s1;\n"
" past_key[output_offset+max_len+max_len+3]=key_vec3.s2;\n"
" past_key[output_offset+max_len+max_len+max_len+3]=key_vec3.s3;\n"
" }\n"
"}\n"
"__kernel void rearrange_v(GLOBAL_SIZE_3_DIMS\n"
" __global const FLOAT *value,// [batch value_seq_len kv_head_num head_dim]\n"
" __global FLOAT *past_value,// [batch kv_head_num max_length head_dim]\n"
" __private const int past_len,\n"
" __private const int max_len,\n"
" __private const int seq_len,\n"
" __private const int kv_head_num,\n"
" __private const int head_dim) {\n"
" \n"
" const int x=get_global_id(0); // head_dim\n"
" const int y=get_global_id(1); // seq_len decode=1\n"
" int z=get_global_id(2); // kv_head_num\n"
" DEAL_NON_UNIFORM_DIM3(x,y,z);\n"
" \n"
" const int b=z/kv_head_num;\n"
" z=z % kv_head_num;\n"
" const int x4=x << 2;\n"
" \n"
"#ifdef OPENCL_PREFILL_ATTENTION\n"
" const int y4=y << 2;\n"
" const int stride=kv_head_num*head_dim;\n"
" int value_offset=((b*seq_len+y4)*kv_head_num+z)*head_dim+x4;\n"
" FLOAT4 value_vec0=vload4(0,value+value_offset); value_offset += stride;\n"
" FLOAT4 value_vec1=(y4+1 >= seq_len) ? (FLOAT4)0 : vload4(0,value+value_offset); value_offset += stride;\n"
" FLOAT4 value_vec2=(y4+2 >= seq_len) ? (FLOAT4)0 : vload4(0,value+value_offset); value_offset += stride;\n"
" FLOAT4 value_vec3=(y4+3 >= seq_len) ? (FLOAT4)0 : vload4(0,value+value_offset);\n"
" const int output_offset=((b*kv_head_num+z)*max_len+past_len+y4)*head_dim+x4;\n"
" vstore4(value_vec0,0,past_value+output_offset);\n"
" vstore4(value_vec1,0,past_value+output_offset+head_dim);\n"
" vstore4(value_vec2,0,past_value+output_offset+head_dim+head_dim);\n"
" vstore4(value_vec3,0,past_value+output_offset+head_dim+head_dim+head_dim);\n"
"#else\n"
" FLOAT4 value_vec=vload4(0,value+(b*kv_head_num+z)*head_dim+x4);\n"
" const int output_offset=((b*kv_head_num+z)*max_len+past_len)*head_dim+x4;\n"
" vstore4(value_vec,0,past_value+output_offset);\n"
"#endif\n"
"}\n"
"__kernel void rearrange_v_packed(GLOBAL_SIZE_3_DIMS\n"
" __global const FLOAT *value,// [sum_seq_len,kv_head_num,head_dim]\n"
" __global FLOAT *past_value,// packed by request: [kv_head_num,max_len,head_dim]\n"
" __global const int *meta0,// [ioOffsetTokens,seqLen,pastLen,maxLen]\n"
" __global const int *meta1,// [qBaseElems,qkBaseElems,keyBaseElems,valueBaseElems]\n"
" __private const int kv_head_num,\n"
" __private const int head_dim) {\n"
" const int x=get_global_id(0); // head_dim/4\n"
" const int y=get_global_id(1); // seq_len/4\n"
" const int z=get_global_id(2); // req_count*kv_head_num\n"
" DEAL_NON_UNIFORM_DIM3(x,y,z);\n"
" const int req=z/kv_head_num;\n"
" const int hn=z % kv_head_num;\n"
" const int seq_len=meta0[req*4+1];\n"
" const int past_len=meta0[req*4+2];\n"
" const int max_len=meta0[req*4+3];\n"
" const int io_offset=meta0[req*4+0];\n"
" const int value_base=meta1[req*4+3];\n"
" const int y4=y << 2;\n"
" if (y4 >= seq_len) {\n"
" return;\n"
" }\n"
" const int x4=x << 2;\n"
" const int stride=kv_head_num*head_dim;\n"
" int value_offset=((io_offset+y4)*kv_head_num+hn)*head_dim+x4;\n"
" FLOAT4 value_vec0=vload4(0,value+value_offset); value_offset += stride;\n"
" FLOAT4 value_vec1=(y4+1 >= seq_len) ? (FLOAT4)0 : vload4(0,value+value_offset); value_offset += stride;\n"
" FLOAT4 value_vec2=(y4+2 >= seq_len) ? (FLOAT4)0 : vload4(0,value+value_offset); value_offset += stride;\n"
" FLOAT4 value_vec3=(y4+3 >= seq_len) ? (FLOAT4)0 : vload4(0,value+value_offset);\n"
" const int output_offset=value_base+((hn*max_len+past_len+y4)*head_dim+x4);\n"
" if (past_len+y4<max_len) {\n"
" vstore4(value_vec0,0,past_value+output_offset);\n"
" }\n"
" if (y4+1<seq_len && past_len+y4+1<max_len) {\n"
" vstore4(value_vec1,0,past_value+output_offset+head_dim);\n"
" }\n"
" if (y4+2<seq_len && past_len+y4+2<max_len) {\n"
" vstore4(value_vec2,0,past_value+output_offset+head_dim+head_dim);\n"
" }\n"
" if (y4+3<seq_len && past_len+y4+3<max_len) {\n"
" vstore4(value_vec3,0,past_value+output_offset+head_dim+head_dim+head_dim);\n"
" }\n"
"}\n"
"__kernel void rearrange_mask_shortprefill(GLOBAL_SIZE_3_DIMS\n"
" #ifdef ADD_MASK\n"
" __global const FLOAT* mask,\n"
" __global FLOAT* maskout,\n"
" #else\n"
" __global const int* mask,// [1 1 query_seq_len mask_key_seq_len4]\n"
" __global int* maskout,// [1 1 mask_key_seq_len4 query_seq_len4]\n"
" #endif\n"
" __private const int query_seq_len,\n"
" __private const int mask_key_seq_len){\n"
" const int x=get_global_id(0); // query_seq_len4\n"
" const int y=get_global_id(1); // mask_key_seq_len4\n"
" const int z=get_global_id(2); // batch\n"
" DEAL_NON_UNIFORM_DIM3(x,y,z);\n"
" \n"
" const int x4=x << 2;\n"
" const int y4=y << 2;\n"
" float4 mask_tmp0,mask_tmp1,mask_tmp2,mask_tmp3;\n"
" float4 mask0,mask1,mask2,mask3;\n"
" int mask_offset=x4*mask_key_seq_len+y4;\n"
" if(x4+3<query_seq_len && y4+3<mask_key_seq_len){\n"
" mask_tmp0=convert_float4(vload4(0,mask+mask_offset)); mask_offset += mask_key_seq_len;\n"
" mask_tmp1=convert_float4(vload4(0,mask+mask_offset)); mask_offset += mask_key_seq_len;\n"
" mask_tmp2=convert_float4(vload4(0,mask+mask_offset)); mask_offset += mask_key_seq_len;\n"
" mask_tmp3=convert_float4(vload4(0,mask+mask_offset));\n"
" } else{\n"
" if(y4+3<mask_key_seq_len){\n"
" mask_tmp0=convert_float4(vload4(0,mask+mask_offset)); mask_offset += mask_key_seq_len;\n"
" mask_tmp1=(x4+1 >= query_seq_len) ? (float4)0 : convert_float4(vload4(0,mask+mask_offset)); mask_offset += mask_key_seq_len;\n"
" mask_tmp2=(x4+2 >= query_seq_len) ? (float4)0 : convert_float4(vload4(0,mask+mask_offset)); mask_offset += mask_key_seq_len;\n"
" mask_tmp3=(x4+3 >= query_seq_len) ? (float4)0 : convert_float4(vload4(0,mask+mask_offset));\n"
" } else if(y4+1 == mask_key_seq_len){\n"
" mask_tmp0=(float4)(mask[mask_offset],0,0,0); mask_offset += mask_key_seq_len;\n"
" mask_tmp1=(x4+1 >= query_seq_len) ? (float4)0 : (float4)(mask[mask_offset],0,0,0); mask_offset += mask_key_seq_len;\n"
" mask_tmp2=(x4+2 >= query_seq_len) ? (float4)0 : (float4)(mask[mask_offset],0,0,0); mask_offset += mask_key_seq_len;\n"
" mask_tmp3=(x4+3 >= query_seq_len) ? (float4)0 : (float4)(mask[mask_offset],0,0,0);\n"
" }else if(y4+2 == mask_key_seq_len){\n"
" mask_tmp0=(float4)(mask[mask_offset],mask[mask_offset+1],0,0); mask_offset += mask_key_seq_len;\n"
" mask_tmp1=(x4+1 >= query_seq_len) ? (float4)0 : (float4)(mask[mask_offset],mask[mask_offset+1],0,0); mask_offset += mask_key_seq_len;\n"
" mask_tmp2=(x4+2 >= query_seq_len) ? (float4)0 : (float4)(mask[mask_offset],mask[mask_offset+1],0,0); mask_offset += mask_key_seq_len;\n"
" mask_tmp3=(x4+3 >= query_seq_len) ? (float4)0 : (float4)(mask[mask_offset],mask[mask_offset+1],0,0);\n"
" }else if(y4+3 == mask_key_seq_len){\n"
" mask_tmp0=(float4)(mask[mask_offset],mask[mask_offset+1],mask[mask_offset+2],0); mask_offset += mask_key_seq_len;\n"
" mask_tmp1=(x4+1 >= query_seq_len) ? (float4)0 : (float4)(mask[mask_offset],mask[mask_offset+1],mask[mask_offset+2],0); mask_offset += mask_key_seq_len;\n"
" mask_tmp2=(x4+2 >= query_seq_len) ? (float4)0 : (float4)(mask[mask_offset],mask[mask_offset+1],mask[mask_offset+2],0); mask_offset += mask_key_seq_len;\n"
" mask_tmp3=(x4+3 >= query_seq_len) ? (float4)0 : (float4)(mask[mask_offset],mask[mask_offset+1],mask[mask_offset+2],0);\n"
" }\n"
" }\n"
" mask0=(float4)(mask_tmp0.s0,mask_tmp1.s0,mask_tmp2.s0,mask_tmp3.s0);\n"
" mask1=(float4)(mask_tmp0.s1,mask_tmp1.s1,mask_tmp2.s1,mask_tmp3.s1);\n"
" mask2=(float4)(mask_tmp0.s2,mask_tmp1.s2,mask_tmp2.s2,mask_tmp3.s2);\n"
" mask3=(float4)(mask_tmp0.s3,mask_tmp1.s3,mask_tmp2.s3,mask_tmp3.s3);\n"
" \n"
" int query_seq_len4=((query_seq_len+3)/4)*4;\n"
" int output_offset=y4*query_seq_len4+x4;\n"
" #ifdef ADD_MASK\n"
" vstore4(CONVERT_FLOAT4(mask0),0,maskout+output_offset);\n"
" vstore4(CONVERT_FLOAT4(mask1),0,maskout+output_offset+query_seq_len4);\n"
" vstore4(CONVERT_FLOAT4(mask2),0,maskout+output_offset+query_seq_len4+query_seq_len4);\n"
" vstore4(CONVERT_FLOAT4(mask3),0,maskout+output_offset+query_seq_len4+query_seq_len4+query_seq_len4);\n"
" #else\n"
" vstore4(convert_int4(mask0),0,maskout+output_offset);\n"
" vstore4(convert_int4(mask1),0,maskout+output_offset+query_seq_len4);\n"
" vstore4(convert_int4(mask2),0,maskout+output_offset+query_seq_len4+query_seq_len4);\n"
" vstore4(convert_int4(mask3),0,maskout+output_offset+query_seq_len4+query_seq_len4+query_seq_len4);\n"
" #endif\n"
"}\n"
"__kernel void rearrange_mask_shortprefill_packed(GLOBAL_SIZE_3_DIMS\n"
" #ifdef ADD_MASK\n"
" __global const FLOAT* mask,\n"
" __global FLOAT* maskout,\n"
" #else\n"
" __global const int* mask,\n"
" __global int* maskout,\n"
" #endif\n"
" __global const int *meta0,\n"
" __global const int *meta2) {\n"
" const int x=get_global_id(0); // query_seq_len4\n"
" const int y=get_global_id(1); // mask_key_seq_len4\n"
" const int req=get_global_id(2);\n"
" DEAL_NON_UNIFORM_DIM3(x,y,req);\n"
" const int query_seq_len=meta0[req*4+1];\n"
" const int query_seq_len4=((query_seq_len+3)/4)*4;\n"
" const int mask_input_offset=meta2[req*4+0];\n"
" const int mask_output_offset=meta2[req*4+1];\n"
" const int mask_stride=meta2[req*4+3];\n"
" const int x4=x << 2;\n"
" const int y4=y << 2;\n"
" if (x4 >= query_seq_len || y4 >= mask_stride) {\n"
" return;\n"
" }\n"
" float4 mask_tmp0,mask_tmp1,mask_tmp2,mask_tmp3;\n"
" float4 mask0,mask1,mask2,mask3;\n"
" int mask_offset=mask_input_offset+x4*mask_stride+y4;\n"
" if (x4+3<query_seq_len && y4+3<mask_stride) {\n"
" mask_tmp0=convert_float4(vload4(0,mask+mask_offset)); mask_offset += mask_stride;\n"
" mask_tmp1=convert_float4(vload4(0,mask+mask_offset)); mask_offset += mask_stride;\n"
" mask_tmp2=convert_float4(vload4(0,mask+mask_offset)); mask_offset += mask_stride;\n"
" mask_tmp3=convert_float4(vload4(0,mask+mask_offset));\n"
" } else {\n"
" if (y4+3<mask_stride) {\n"
" mask_tmp0=convert_float4(vload4(0,mask+mask_offset)); mask_offset += mask_stride;\n"
" mask_tmp1=(x4+1 >= query_seq_len) ? (float4)0 : convert_float4(vload4(0,mask+mask_offset)); mask_offset += mask_stride;\n"
" mask_tmp2=(x4+2 >= query_seq_len) ? (float4)0 : convert_float4(vload4(0,mask+mask_offset)); mask_offset += mask_stride;\n"
" mask_tmp3=(x4+3 >= query_seq_len) ? (float4)0 : convert_float4(vload4(0,mask+mask_offset));\n"
" } else if (y4+1 == mask_stride) {\n"
" mask_tmp0=(float4)(mask[mask_offset],0,0,0); mask_offset += mask_stride;\n"
" mask_tmp1=(x4+1 >= query_seq_len) ? (float4)0 : (float4)(mask[mask_offset],0,0,0); mask_offset += mask_stride;\n"
" mask_tmp2=(x4+2 >= query_seq_len) ? (float4)0 : (float4)(mask[mask_offset],0,0,0); mask_offset += mask_stride;\n"
" mask_tmp3=(x4+3 >= query_seq_len) ? (float4)0 : (float4)(mask[mask_offset],0,0,0);\n"
" } else if (y4+2 == mask_stride) {\n"
" mask_tmp0=(float4)(mask[mask_offset],mask[mask_offset+1],0,0); mask_offset += mask_stride;\n"
" mask_tmp1=(x4+1 >= query_seq_len) ? (float4)0 : (float4)(mask[mask_offset],mask[mask_offset+1],0,0); mask_offset += mask_stride;\n"
" mask_tmp2=(x4+2 >= query_seq_len) ? (float4)0 : (float4)(mask[mask_offset],mask[mask_offset+1],0,0); mask_offset += mask_stride;\n"
" mask_tmp3=(x4+3 >= query_seq_len) ? (float4)0 : (float4)(mask[mask_offset],mask[mask_offset+1],0,0);\n"
" } else {\n"
" mask_tmp0=(float4)(mask[mask_offset],mask[mask_offset+1],mask[mask_offset+2],0); mask_offset += mask_stride;\n"
" mask_tmp1=(x4+1 >= query_seq_len) ? (float4)0 : (float4)(mask[mask_offset],mask[mask_offset+1],mask[mask_offset+2],0); mask_offset += mask_stride;\n"
" mask_tmp2=(x4+2 >= query_seq_len) ? (float4)0 : (float4)(mask[mask_offset],mask[mask_offset+1],mask[mask_offset+2],0); mask_offset += mask_stride;\n"
" mask_tmp3=(x4+3 >= query_seq_len) ? (float4)0 : (float4)(mask[mask_offset],mask[mask_offset+1],mask[mask_offset+2],0);\n"
" }\n"
" }\n"
" mask0=(float4)(mask_tmp0.s0,mask_tmp1.s0,mask_tmp2.s0,mask_tmp3.s0);\n"
" mask1=(float4)(mask_tmp0.s1,mask_tmp1.s1,mask_tmp2.s1,mask_tmp3.s1);\n"
" mask2=(float4)(mask_tmp0.s2,mask_tmp1.s2,mask_tmp2.s2,mask_tmp3.s2);\n"
" mask3=(float4)(mask_tmp0.s3,mask_tmp1.s3,mask_tmp2.s3,mask_tmp3.s3);\n"
" int output_offset=mask_output_offset+y4*query_seq_len4+x4;\n"
" #ifdef ADD_MASK\n"
" vstore4(CONVERT_FLOAT4(mask0),0,maskout+output_offset);\n"
" vstore4(CONVERT_FLOAT4(mask1),0,maskout+output_offset+query_seq_len4);\n"
" vstore4(CONVERT_FLOAT4(mask2),0,maskout+output_offset+query_seq_len4+query_seq_len4);\n"
" vstore4(CONVERT_FLOAT4(mask3),0,maskout+output_offset+query_seq_len4+query_seq_len4+query_seq_len4);\n"
" #else\n"
" vstore4(convert_int4(mask0),0,maskout+output_offset);\n"
" vstore4(convert_int4(mask1),0,maskout+output_offset+query_seq_len4);\n"
" vstore4(convert_int4(mask2),0,maskout+output_offset+query_seq_len4+query_seq_len4);\n"
" vstore4(convert_int4(mask3),0,maskout+output_offset+query_seq_len4+query_seq_len4+query_seq_len4);\n"
" #endif\n"
"}\n"
"__kernel void matmul_qk_div_mask_prefill(GLOBAL_SIZE_3_DIMS\n"
" __global const FLOAT *query,// [batch head_num head_dim_4 query_seq_len_4]\n"
" __global const FLOAT *past_key,// [batch kv_head_num head_dim_4 kv_max_length]\n"
" #ifdef ADD_MASK\n"
" __global const FLOAT* mask,\n"
" #elif defined(SET_MASK)\n"
" __global const int* mask,// [1 1 query_seq_len mask_key_seq_len]\n"
" #endif\n"
" __global FLOAT *qk,// [batch head_num kv_seq_length query_seq_len_4]\n"
" __private const float scale,\n"
" __private const int query_seq_len,\n"
" __private const int mask_key_seq_len,\n"
" __private const int key_seq_len,\n"
" __private const int max_len,\n"
" __private const int head_num,\n"
" __private const int head_dim) {\n"
" \n"
" const int x=get_global_id(0); // query_seq_len\n"
" const int y=get_global_id(1); // kv_seq_length\n"
" const int z=get_global_id(2); // head_num*batch\n"
" DEAL_NON_UNIFORM_DIM3(x,y,z);\n"
" \n"
" const int x4=x << 2;\n"
" const int y4=y << 2;\n"
" \n"
" const int query_seq_len4=(query_seq_len+3)/4*4;;\n"
" const int query_offset=z*head_dim*query_seq_len4+x4;\n"
" const int past_offset=(z/NUMHEAD_GROUP_SIZE)*head_dim*max_len+y4;\n"
" float4 out0=0,out1=0,out2=0,out3=0;\n"
" \n"
" for(int i=0; i<head_dim/4; ++i){\n"
" int i4=i << 2;\n"
" float4 query_vec0=convert_float4(vload4(0,query+query_offset+i4*query_seq_len4));\n"
" float4 query_vec1=convert_float4(vload4(0,query+query_offset+(i4+1)*query_seq_len4));\n"
" float4 query_vec2=convert_float4(vload4(0,query+query_offset+(i4+2)*query_seq_len4));\n"
" float4 query_vec3=convert_float4(vload4(0,query+query_offset+(i4+3)*query_seq_len4));\n"
" \n"
" float4 past_vec0=convert_float4(vload4(0,past_key+past_offset+i4*max_len));\n"
" float4 past_vec1=convert_float4(vload4(0,past_key+past_offset+(i4+1)*max_len));\n"
" float4 past_vec2=convert_float4(vload4(0,past_key+past_offset+(i4+2)*max_len));\n"
" float4 past_vec3=convert_float4(vload4(0,past_key+past_offset+(i4+3)*max_len));\n"
" out0=mad((float4)past_vec0.s0,query_vec0,out0);\n"
" out0=mad((float4)past_vec1.s0,query_vec1,out0);\n"
" out0=mad((float4)past_vec2.s0,query_vec2,out0);\n"
" out0=mad((float4)past_vec3.s0,query_vec3,out0);\n"
" \n"
" out1=mad((float4)past_vec0.s1,query_vec0,out1);\n"
" out1=mad((float4)past_vec1.s1,query_vec1,out1);\n"
" out1=mad((float4)past_vec2.s1,query_vec2,out1);\n"
" out1=mad((float4)past_vec3.s1,query_vec3,out1);\n"
" \n"
" out2=mad((float4)past_vec0.s2,query_vec0,out2);\n"
" out2=mad((float4)past_vec1.s2,query_vec1,out2);\n"
" out2=mad((float4)past_vec2.s2,query_vec2,out2);\n"
" out2=mad((float4)past_vec3.s2,query_vec3,out2);\n"
" \n"
" out3=mad((float4)past_vec0.s3,query_vec0,out3);\n"
" out3=mad((float4)past_vec1.s3,query_vec1,out3);\n"
" out3=mad((float4)past_vec2.s3,query_vec2,out3);\n"
" out3=mad((float4)past_vec3.s3,query_vec3,out3);\n"
" }\n"
" out0 *= (float4)scale;\n"
" out1 *= (float4)scale;\n"
" out2 *= (float4)scale;\n"
" out3 *= (float4)scale;\n"
" {\n"
" #if defined(ADD_MASK) || defined(SET_MASK)\n"
" int query_seq_len4=((query_seq_len+3)/4)*4;\n"
" int mask_clp=y4+mask_key_seq_len-key_seq_len;\n"
" int mask_offset=mask_clp*query_seq_len4+x4;\n"
" float4 mask0=mask_clp >= 0 && mask_clp<mask_key_seq_len ? convert_float4(vload4(0,mask+mask_offset)) : 0; mask_offset += query_seq_len4;\n"
" float4 mask1=mask_clp+1 >= 0 && mask_clp+1<mask_key_seq_len? convert_float4(vload4(0,mask+mask_offset)) : 0; mask_offset += query_seq_len4;\n"
" float4 mask2=mask_clp+2 >= 0 && mask_clp+2<mask_key_seq_len? convert_float4(vload4(0,mask+mask_offset)) : 0; mask_offset += query_seq_len4;\n"
" float4 mask3=mask_clp+3 >= 0 && mask_clp+3<mask_key_seq_len? convert_float4(vload4(0,mask+mask_offset)) : 0;\n"
" #endif\n"
" \n"
" #ifdef ADD_MASK\n"
" out0 += mask0;\n"
" out1 += mask1;\n"
" out2 += mask2;\n"
" out3 += mask3;\n"
" #elif defined(SET_MASK)\n"
" out0=(mask0 == (float4)0) ? (float4)(-FLT_MAX) : out0;\n"
" out1=(mask1 == (float4)0) ? (float4)(-FLT_MAX) : out1;\n"
" out2=(mask2 == (float4)0) ? (float4)(-FLT_MAX) : out2;\n"
" out3=(mask3 == (float4)0) ? (float4)(-FLT_MAX) : out3;\n"
" #endif\n"
" }\n"
" \n"
" const int qk_offset=(z*key_seq_len+y4)*query_seq_len4+x4;\n"
" vstore4(CONVERT_FLOAT4(out0),0,qk+qk_offset);\n"
" if(y4+1 >= key_seq_len) return;\n"
" vstore4(CONVERT_FLOAT4(out1),0,qk+qk_offset+query_seq_len4);\n"
" if(y4+2 >= key_seq_len) return;\n"
" vstore4(CONVERT_FLOAT4(out2),0,qk+qk_offset+query_seq_len4+query_seq_len4);\n"
" if(y4+3 >= key_seq_len) return;\n"
" vstore4(CONVERT_FLOAT4(out3),0,qk+qk_offset+query_seq_len4+query_seq_len4+query_seq_len4);\n"
"}\n"
"__kernel void matmul_qk_div_mask_prefill_packed(GLOBAL_SIZE_3_DIMS\n"
" __global const FLOAT *query,// packed by request: [head_num head_dim seq_len4]\n"
" __global const FLOAT *past_key,// packed by request: [kv_head_num head_dim max_len]\n"
" #ifdef ADD_MASK\n"
" __global const FLOAT* mask,\n"
" #elif defined(SET_MASK)\n"
" __global const int* mask,\n"
" #endif\n"
" __global FLOAT *qk,// packed by request: [head_num kv_seq_len seq_len4]\n"
" __global const int *meta0,\n"
" __global const int *meta1,\n"
" __global const int *meta2,\n"
" __private const float scale,\n"
" __private const int head_num,\n"
" __private const int head_dim) {\n"
" const int x=get_global_id(0); // query_seq_len/4\n"
" const int y=get_global_id(1); // kv_seq_len/4\n"
" const int z=get_global_id(2); // req_count*head_num\n"
" DEAL_NON_UNIFORM_DIM3(x,y,z);\n"
" const int req=z/head_num;\n"
" const int hn=z % head_num;\n"
" const int seq_len=meta0[req*4+1];\n"
" const int past_len=meta0[req*4+2];\n"
" const int max_len=meta0[req*4+3];\n"
" const int query_base=meta1[req*4+0];\n"
" const int qk_base=meta1[req*4+1];\n"
" const int key_base=meta1[req*4+2];\n"
" const int mask_base=meta2[req*4+1];\n"
" const int key_seq_len=meta2[req*4+2];\n"
" const int x4=x << 2;\n"
" const int y4=y << 2;\n"
" const int query_seq_len4=(seq_len+3)/4*4;\n"
" if (x4 >= query_seq_len4 || y4 >= key_seq_len) {\n"
" return;\n"
" }\n"
" const int query_offset=query_base+hn*head_dim*query_seq_len4+x4;\n"
" const int past_offset=key_base+(hn/NUMHEAD_GROUP_SIZE)*head_dim*max_len+y4;\n"
" float4 out0=0,out1=0,out2=0,out3=0;\n"
" for (int i=0; i<head_dim/4; ++i) {\n"
" int i4=i << 2;\n"
" float4 query_vec0=convert_float4(vload4(0,query+query_offset+i4*query_seq_len4));\n"
" float4 query_vec1=convert_float4(vload4(0,query+query_offset+(i4+1)*query_seq_len4));\n"
" float4 query_vec2=convert_float4(vload4(0,query+query_offset+(i4+2)*query_seq_len4));\n"
" float4 query_vec3=convert_float4(vload4(0,query+query_offset+(i4+3)*query_seq_len4));\n"
" float4 past_vec0=convert_float4(vload4(0,past_key+past_offset+i4*max_len));\n"
" float4 past_vec1=convert_float4(vload4(0,past_key+past_offset+(i4+1)*max_len));\n"
" float4 past_vec2=convert_float4(vload4(0,past_key+past_offset+(i4+2)*max_len));\n"
" float4 past_vec3=convert_float4(vload4(0,past_key+past_offset+(i4+3)*max_len));\n"
" out0=mad((float4)past_vec0.s0,query_vec0,out0);\n"
" out0=mad((float4)past_vec1.s0,query_vec1,out0);\n"
" out0=mad((float4)past_vec2.s0,query_vec2,out0);\n"
" out0=mad((float4)past_vec3.s0,query_vec3,out0);\n"
" out1=mad((float4)past_vec0.s1,query_vec0,out1);\n"
" out1=mad((float4)past_vec1.s1,query_vec1,out1);\n"
" out1=mad((float4)past_vec2.s1,query_vec2,out1);\n"
" out1=mad((float4)past_vec3.s1,query_vec3,out1);\n"
" out2=mad((float4)past_vec0.s2,query_vec0,out2);\n"
" out2=mad((float4)past_vec1.s2,query_vec1,out2);\n"
" out2=mad((float4)past_vec2.s2,query_vec2,out2);\n"
" out2=mad((float4)past_vec3.s2,query_vec3,out2);\n"
" out3=mad((float4)past_vec0.s3,query_vec0,out3);\n"
" out3=mad((float4)past_vec1.s3,query_vec1,out3);\n"
" out3=mad((float4)past_vec2.s3,query_vec2,out3);\n"
" out3=mad((float4)past_vec3.s3,query_vec3,out3);\n"
" }\n"
" out0 *= (float4)scale;\n"
" out1 *= (float4)scale;\n"
" out2 *= (float4)scale;\n"
" out3 *= (float4)scale;\n"
" #if defined(ADD_MASK) || defined(SET_MASK)\n"
" const int mask_stride=meta2[req*4+3];\n"
" const int mask_gap=key_seq_len-mask_stride;\n"
" #ifdef ADD_MASK\n"
" #define APPLY_PACKED_MASK(score, key_index) "" { "" const int mask_index = (key_index) - mask_gap; "" if (mask_index >= 0 && mask_index < mask_stride) { "" const int mask_offset = mask_base + mask_index * query_seq_len4 + x4; "" const float4 mask_value = convert_float4(vload4(0, mask + mask_offset)); "" /* Square masks cover only current tokens; full masks cover the whole KV span. */ "" score = score + mask_value; "" } "" }\n"
" #else\n"
" #define APPLY_PACKED_MASK(score, key_index) "" { "" const int mask_index = (key_index) - mask_gap; "" if (mask_index >= 0 && mask_index < mask_stride) { "" const int mask_offset = mask_base + mask_index * query_seq_len4 + x4; "" const float4 mask_value = convert_float4(vload4(0, mask + mask_offset)); "" /* Square masks cover only current tokens; full masks cover the whole KV span. */ "" if (mask_value.s0 == 0.0f) { score.s0 = -FLT_MAX; } "" if (mask_value.s1 == 0.0f) { score.s1 = -FLT_MAX; } "" if (mask_value.s2 == 0.0f) { score.s2 = -FLT_MAX; } "" if (mask_value.s3 == 0.0f) { score.s3 = -FLT_MAX; } "" } "" }\n"
" #endif\n"
" APPLY_PACKED_MASK(out0,y4);\n"
" APPLY_PACKED_MASK(out1,y4+1);\n"
" APPLY_PACKED_MASK(out2,y4+2);\n"
" APPLY_PACKED_MASK(out3,y4+3);\n"
" #undef APPLY_PACKED_MASK\n"
" #endif\n"
" const int qk_offset=qk_base+(hn*key_seq_len+y4)*query_seq_len4+x4;\n"
" if (y4<key_seq_len) {\n"
" vstore4(CONVERT_FLOAT4(out0),0,qk+qk_offset);\n"
" }\n"
" if (y4+1<key_seq_len) {\n"
" vstore4(CONVERT_FLOAT4(out1),0,qk+qk_offset+query_seq_len4);\n"
" }\n"
" if (y4+2<key_seq_len) {\n"
" vstore4(CONVERT_FLOAT4(out2),0,qk+qk_offset+query_seq_len4+query_seq_len4);\n"
" }\n"
" if (y4+3<key_seq_len) {\n"
" vstore4(CONVERT_FLOAT4(out3),0,qk+qk_offset+query_seq_len4+query_seq_len4+query_seq_len4);\n"
" }\n"
"}\n"
"__kernel void matmul_qk_decode(GLOBAL_SIZE_2_DIMS\n"
" __global const FLOAT *query,// key [1 head_num head_dim]\n"
" __global const FLOAT *past_key,// [1 head_num head_dim max_length]\n"
" __global FLOAT *qk,// [1 head_num key_seq_len 1]\n"
" __private const float scale,\n"
" __private const int seq_len,\n"
" __private const int max_len,\n"
" __private const int head_num,\n"
" __private const int head_dim) {\n"
" \n"
" const int x=get_global_id(0); // key_seq_len\n"
" const int y=get_global_id(1); // head_num\n"
" DEAL_NON_UNIFORM_DIM2(x,y);\n"
" const int x4=x << 2;\n"
" \n"
" const int query_offset=y*head_dim;\n"
" const int past_offset=(y/NUMHEAD_GROUP_SIZE)*head_dim*max_len+x4;\n"
" float4 out0=0;\n"
" \n"
" for(int i=0; i<head_dim/4; ++i){\n"
" int i4=i << 2;\n"
" float4 query_vec=convert_float4(vload4(0,query+query_offset+i4));\n"
" \n"
" float4 past_vec0=convert_float4(vload4(0,past_key+past_offset+i4*max_len));\n"
" float4 past_vec1=convert_float4(vload4(0,past_key+past_offset+(i4+1)*max_len));\n"
" float4 past_vec2=convert_float4(vload4(0,past_key+past_offset+(i4+2)*max_len));\n"
" float4 past_vec3=convert_float4(vload4(0,past_key+past_offset+(i4+3)*max_len));\n"
" \n"
" out0=mad((float4)query_vec.s0,past_vec0,out0);\n"
" out0=mad((float4)query_vec.s1,past_vec1,out0);\n"
" out0=mad((float4)query_vec.s2,past_vec2,out0);\n"
" out0=mad((float4)query_vec.s3,past_vec3,out0);\n"
" }\n"
" out0 *= (float4)scale;\n"
" const int qk_offset=y*seq_len+x4;\n"
" if(x4+3<seq_len){\n"
" vstore4(CONVERT_FLOAT4(out0),0,qk+qk_offset);\n"
" }else {\n"
" int remain=seq_len-x4;\n"
" if(remain == 3){\n"
" vstore3(CONVERT_FLOAT3((float3)(out0.s012)),0,qk+qk_offset);\n"
" } else if(remain == 2){\n"
" vstore2(CONVERT_FLOAT2((float2)(out0.s01)),0,qk+qk_offset);\n"
" }else if(remain == 1){\n"
" qk[qk_offset]=out0.s0;\n"
" }\n"
" }\n"
"}\n"
"__kernel void matmul_qk_decode_packed(GLOBAL_SIZE_2_DIMS\n"
" __global const FLOAT *query,// [sum_seq_len head_num head_dim]\n"
" __global const FLOAT *past_key,// packed by request: [kv_head_num head_dim max_len]\n"
" __global FLOAT *qk,// packed scalar decode: [head_num kv_seq_len]\n"
" __global const int *meta0,\n"
" __global const int *meta1,\n"
" __global const int *meta2,\n"
" __private const float scale,\n"
" __private const int head_num,\n"
" __private const int head_dim) {\n"
" const int x=get_global_id(0); // kv_seq_len/4\n"
" const int z=get_global_id(1); // req_count*head_num\n"
" DEAL_NON_UNIFORM_DIM2(x,z);\n"
" const int req=z/head_num;\n"
" const int hn=z % head_num;\n"
" const int io_offset=meta0[req*4+0];\n"
" const int max_len=meta0[req*4+3];\n"
" const int qk_base=meta1[req*4+1];\n"
" const int key_base=meta1[req*4+2];\n"
" const int kv_seq_len=meta2[req*4+2];\n"
" const int x4=x << 2;\n"
" if (x4 >= kv_seq_len) {\n"
" return;\n"
" }\n"
" const int query_offset=(io_offset*head_num+hn)*head_dim;\n"
" const int past_offset=key_base+(hn/NUMHEAD_GROUP_SIZE)*head_dim*max_len+x4;\n"
" float4 out0=0;\n"
" for (int i=0; i<head_dim/4; ++i) {\n"
" int i4=i << 2;\n"
" float4 query_vec=convert_float4(vload4(0,query+query_offset+i4));\n"
" float4 past_vec0=convert_float4(vload4(0,past_key+past_offset+i4*max_len));\n"
" float4 past_vec1=convert_float4(vload4(0,past_key+past_offset+(i4+1)*max_len));\n"
" float4 past_vec2=convert_float4(vload4(0,past_key+past_offset+(i4+2)*max_len));\n"
" float4 past_vec3=convert_float4(vload4(0,past_key+past_offset+(i4+3)*max_len));\n"
" out0=mad((float4)query_vec.s0,past_vec0,out0);\n"
" out0=mad((float4)query_vec.s1,past_vec1,out0);\n"
" out0=mad((float4)query_vec.s2,past_vec2,out0);\n"
" out0=mad((float4)query_vec.s3,past_vec3,out0);\n"
" }\n"
" out0 *= (float4)scale;\n"
" const int qk_offset=qk_base+hn*kv_seq_len+x4;\n"
" if (x4+3<kv_seq_len) {\n"
" vstore4(CONVERT_FLOAT4(out0),0,qk+qk_offset);\n"
" } else {\n"
" int remain=kv_seq_len-x4;\n"
" if (remain == 3) {\n"
" vstore3(CONVERT_FLOAT3((float3)(out0.s012)),0,qk+qk_offset);\n"
" } else if (remain == 2) {\n"
" vstore2(CONVERT_FLOAT2((float2)(out0.s01)),0,qk+qk_offset);\n"
" } else if (remain == 1) {\n"
" qk[qk_offset]=out0.s0;\n"
" }\n"
" }\n"
"}\n"
"__kernel void softmax_in1_buf_packed(GLOBAL_SIZE_3_DIMS\n"
" __global const FLOAT *input,\n"
" __global FLOAT *output,\n"
" __global const int *meta1,\n"
" __global const int *meta2,\n"
" __private const int head_num) {\n"
" const int x=get_global_id(0);\n"
" const int y=get_global_id(1); // inside=1\n"
" const int z=get_global_id(2); // req_count*head_num\n"
" DEAL_NON_UNIFORM_DIM3(x,y,z);\n"
" const int req=z/head_num;\n"
" const int hn=z % head_num;\n"
" const int dim=meta2[req*4+2];\n"
" const int qk_base=meta1[req*4+1];\n"
" const int offset=qk_base+hn*dim+y;\n"
" const int dim4=(dim+3)/4;\n"
" const int loop_end=max(0,dim4-1);\n"
"#if SOFTMAX_LOCAL_SIZE >= 4\n"
" int lid=get_local_id(0);\n"
" COMPUTE_FLOAT local sum_mnn[SOFTMAX_LOCAL_SIZE];\n"
" COMPUTE_FLOAT local max_mnn[SOFTMAX_LOCAL_SIZE];\n"
" COMPUTE_FLOAT4 maxValue=(COMPUTE_FLOAT4)-FLT_MAX;\n"
" for (int i=lid; i<loop_end; i += SOFTMAX_LOCAL_SIZE) {\n"
" maxValue=fmax(maxValue,CONVERT_COMPUTE_FLOAT4(vload4(i,input+offset)));\n"
" }\n"
" max_mnn[lid]=fmax(fmax(fmax(maxValue.x,maxValue.y),maxValue.z),maxValue.w);\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" for (int i=SOFTMAX_LOCAL_SIZE/2; i>0; i /= 2) {\n"
" if (lid<i) {\n"
" max_mnn[lid]=fmax(max_mnn[lid],max_mnn[lid+i]);\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" }\n"
" maxValue.x=max_mnn[0];\n"
" for (int i=loop_end << 2; i<dim; ++i) {\n"
" maxValue.x=fmax(maxValue.x,(COMPUTE_FLOAT)(input[offset+i]));\n"
" }\n"
" COMPUTE_FLOAT4 sumValue=(COMPUTE_FLOAT4)0;\n"
" for (int i=lid; i<loop_end; i += SOFTMAX_LOCAL_SIZE) {\n"
" sumValue += exp(CONVERT_COMPUTE_FLOAT4(vload4(i,input+offset))-(COMPUTE_FLOAT4)maxValue.x);\n"
" }\n"
" sum_mnn[lid]=sumValue.x+sumValue.y+sumValue.z+sumValue.w;\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" for (int i=SOFTMAX_LOCAL_SIZE/2; i>0; i /= 2) {\n"
" if (lid<i) {\n"
" sum_mnn[lid]=sum_mnn[lid]+sum_mnn[lid+i];\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" }\n"
" sumValue.x=sum_mnn[0];\n"
" for (int i=loop_end << 2; i<dim; ++i) {\n"
" sumValue.x += exp((COMPUTE_FLOAT)(input[offset+i])-maxValue.x);\n"
" }\n"
" for (int i=lid; i<loop_end; i += SOFTMAX_LOCAL_SIZE) {\n"
" vstore4(CONVERT_FLOAT4(exp(CONVERT_COMPUTE_FLOAT4(vload4(i,input+offset))-(COMPUTE_FLOAT4)maxValue.x)/(COMPUTE_FLOAT4)sumValue.x),\n"
" 0,output+offset+i*4);\n"
" }\n"
" for (int i=loop_end << 2; i<dim; ++i) {\n"
" output[offset+i]=(FLOAT)exp((COMPUTE_FLOAT)(input[offset+i])-maxValue.x)/sumValue.x;\n"
" }\n"
"#else\n"
" COMPUTE_FLOAT4 maxValue=(COMPUTE_FLOAT4)-FLT_MAX;\n"
" for (int i=0; i<loop_end; i++) {\n"
" maxValue=fmax(maxValue,CONVERT_COMPUTE_FLOAT4(vload4(i,input+offset)));\n"
" }\n"
" maxValue.x=fmax(fmax(fmax(maxValue.x,maxValue.y),maxValue.z),maxValue.w);\n"
" for (int i=loop_end << 2; i<dim; ++i) {\n"
" maxValue.x=fmax(maxValue.x,(COMPUTE_FLOAT)(input[offset+i]));\n"
" }\n"
" COMPUTE_FLOAT4 sumValue=(COMPUTE_FLOAT4)0;\n"
" for (int i=0; i<loop_end; i++) {\n"
" sumValue += exp(CONVERT_COMPUTE_FLOAT4(vload4(i,input+offset))-(COMPUTE_FLOAT4)maxValue.x);\n"
" }\n"
" sumValue.x=sumValue.x+sumValue.y+sumValue.z+sumValue.w;\n"
" for (int i=loop_end << 2; i<dim; ++i) {\n"
" sumValue.x += exp((COMPUTE_FLOAT)(input[offset+i])-maxValue.x);\n"
" }\n"
" for (int i=0; i<loop_end; i++) {\n"
" vstore4(CONVERT_FLOAT4(exp(CONVERT_COMPUTE_FLOAT4(vload4(i,input+offset))-(COMPUTE_FLOAT4)maxValue.x)/(COMPUTE_FLOAT4)sumValue.x),\n"
" 0,output+offset+i*4);\n"
" }\n"
" for (int i=loop_end << 2; i<dim; ++i) {\n"
" output[offset+i]=(FLOAT)exp((COMPUTE_FLOAT)(input[offset+i])-maxValue.x)/sumValue.x;\n"
" }\n"
"#endif\n"
"}\n"
"__kernel void matmul_qkv_prefill(GLOBAL_SIZE_3_DIMS\n"
" __global const FLOAT *qk,// qk prefill [batch head_num kv_seq_length query_seq_len]\n"
" __global const FLOAT *past_value,// [batch kv_head_num max_len head_dim]\n"
" __global FLOAT *output,// [batch query_seq_len head_num head_dim]\n"
" __private const int query_seq_len,\n"
" __private const int kv_seq_len,\n"
" __private const int max_len,\n"
" __private const int head_num,\n"
" __private const int kv_head_num,\n"
" __private const int head_dim) {\n"
" \n"
" const int x=get_global_id(0); // head_dim\n"
" const int y=get_global_id(1); // query_seq_len\n"
" int z=get_global_id(2); // head_num*batch\n"
" \n"
" DEAL_NON_UNIFORM_DIM3(x,y,z);\n"
" const int b=z/head_num;\n"
" z=z % head_num;\n"
" const int x8=x << 3;\n"
" const int y4=y << 2;\n"
" \n"
" const int query_seq_len4=(query_seq_len+3)/4*4;\n"
" const int qk_offset=(b*head_num+z)*kv_seq_len*query_seq_len4+y4;\n"
" const int past_offset=((b*kv_head_num+z/NUMHEAD_GROUP_SIZE)*max_len)*head_dim+x8;\n"
" const int loop_end=max(kv_seq_len/4-1,0);\n"
" COMPUTE_FLOAT8 out0=0,out1=0,out2=0,out3=0;\n"
" \n"
" for(int i=0; i<loop_end; ++i){\n"
" int i4=i << 2;\n"
" COMPUTE_FLOAT4 qk_vec0=CONVERT_COMPUTE_FLOAT4(vload4(0,qk+qk_offset+i4*query_seq_len4));\n"
" COMPUTE_FLOAT4 qk_vec1=CONVERT_COMPUTE_FLOAT4(vload4(0,qk+qk_offset+(i4+1)*query_seq_len4));\n"
" COMPUTE_FLOAT4 qk_vec2=CONVERT_COMPUTE_FLOAT4(vload4(0,qk+qk_offset+(i4+2)*query_seq_len4));\n"
" COMPUTE_FLOAT4 qk_vec3=CONVERT_COMPUTE_FLOAT4(vload4(0,qk+qk_offset+(i4+3)*query_seq_len4));\n"
" \n"
" COMPUTE_FLOAT8 past_vec0=CONVERT_COMPUTE_FLOAT8(vload8(0,past_value+past_offset+i4*head_dim));\n"
" COMPUTE_FLOAT8 past_vec1=CONVERT_COMPUTE_FLOAT8(vload8(0,past_value+past_offset+(i4+1)*head_dim));\n"
" COMPUTE_FLOAT8 past_vec2=CONVERT_COMPUTE_FLOAT8(vload8(0,past_value+past_offset+(i4+2)*head_dim));\n"
" COMPUTE_FLOAT8 past_vec3=CONVERT_COMPUTE_FLOAT8(vload8(0,past_value+past_offset+(i4+3)*head_dim));\n"
" \n"
" out0=mad((COMPUTE_FLOAT8)qk_vec0.s0,past_vec0,out0);\n"
" out0=mad((COMPUTE_FLOAT8)qk_vec1.s0,past_vec1,out0);\n"
" out0=mad((COMPUTE_FLOAT8)qk_vec2.s0,past_vec2,out0);\n"
" out0=mad((COMPUTE_FLOAT8)qk_vec3.s0,past_vec3,out0);\n"
" \n"
" out1=mad((COMPUTE_FLOAT8)qk_vec0.s1,past_vec0,out1);\n"
" out1=mad((COMPUTE_FLOAT8)qk_vec1.s1,past_vec1,out1);\n"
" out1=mad((COMPUTE_FLOAT8)qk_vec2.s1,past_vec2,out1);\n"
" out1=mad((COMPUTE_FLOAT8)qk_vec3.s1,past_vec3,out1);\n"
" \n"
" out2=mad((COMPUTE_FLOAT8)qk_vec0.s2,past_vec0,out2);\n"
" out2=mad((COMPUTE_FLOAT8)qk_vec1.s2,past_vec1,out2);\n"
" out2=mad((COMPUTE_FLOAT8)qk_vec2.s2,past_vec2,out2);\n"
" out2=mad((COMPUTE_FLOAT8)qk_vec3.s2,past_vec3,out2);\n"
" \n"
" out3=mad((COMPUTE_FLOAT8)qk_vec0.s3,past_vec0,out3);\n"
" out3=mad((COMPUTE_FLOAT8)qk_vec1.s3,past_vec1,out3);\n"
" out3=mad((COMPUTE_FLOAT8)qk_vec2.s3,past_vec2,out3);\n"
" out3=mad((COMPUTE_FLOAT8)qk_vec3.s3,past_vec3,out3);\n"
" }\n"
" for(int i=(loop_end << 2); i<kv_seq_len; ++i){\n"
" COMPUTE_FLOAT4 qk_vec=CONVERT_COMPUTE_FLOAT4(vload4(0,qk+qk_offset+i*query_seq_len4));\n"
" COMPUTE_FLOAT8 past_vec=CONVERT_COMPUTE_FLOAT8(vload8(0,past_value+past_offset+i*head_dim));\n"
" \n"
" out0=mad((COMPUTE_FLOAT8)qk_vec.s0,past_vec,out0);\n"
" out1=mad((COMPUTE_FLOAT8)qk_vec.s1,past_vec,out1);\n"
" out2=mad((COMPUTE_FLOAT8)qk_vec.s2,past_vec,out2);\n"
" out3=mad((COMPUTE_FLOAT8)qk_vec.s3,past_vec,out3);\n"
" }\n"
" \n"
" const int output_offset=((b*query_seq_len+y4)*head_num+z)*head_dim+x8;\n"
" const int stride=head_num*head_dim;\n"
" vstore8(CONVERT_FLOAT8(out0),0,output+output_offset);\n"
" if(y4+1 >= query_seq_len) return;\n"
" vstore8(CONVERT_FLOAT8(out1),0,output+output_offset+stride);\n"
" if(y4+2 >= query_seq_len) return;\n"
" vstore8(CONVERT_FLOAT8(out2),0,output+output_offset+stride+stride);\n"
" if(y4+3 >= query_seq_len) return;\n"
" vstore8(CONVERT_FLOAT8(out3),0,output+output_offset+stride+stride+stride);\n"
"}\n"
"__kernel void softmax_v4_buf_packed(GLOBAL_SIZE_3_DIMS\n"
" __global const FLOAT *input,// packed by request: [head_num kv_seq_len seq_len4]\n"
" __global FLOAT *output,\n"
" __global const int *meta0,\n"
" __global const int *meta1,\n"
" __global const int *meta2,\n"
" __private const int head_num) {\n"
" const int x=get_global_id(0);\n"
" const int y=get_global_id(1); // seq_len4/4\n"
" const int z=get_global_id(2); // req_count*head_num\n"
" DEAL_NON_UNIFORM_DIM3(x,y,z);\n"
" const int req=z/head_num;\n"
" const int hn=z % head_num;\n"
" const int seq_len=meta0[req*4+1];\n"
" const int kv_seq_len=meta2[req*4+2];\n"
" const int qk_base=meta1[req*4+1];\n"
" const int seq_len4=(seq_len+3)/4*4;\n"
" const int block=y << 2;\n"
" if (block >= seq_len4) {\n"
" return;\n"
" }\n"
" const int offset=qk_base+hn*kv_seq_len*seq_len4+block;\n"
"#if SOFTMAX_LOCAL_SIZE >= 4\n"
" const int lid=get_local_id(0);\n"
" COMPUTE_FLOAT4 local sum_mnn[SOFTMAX_LOCAL_SIZE];\n"
" COMPUTE_FLOAT4 local max_mnn[SOFTMAX_LOCAL_SIZE];\n"
" COMPUTE_FLOAT4 maxValue=(COMPUTE_FLOAT4)-FLT_MAX;\n"
" for (int i=lid; i<kv_seq_len; i += SOFTMAX_LOCAL_SIZE) {\n"
" maxValue=fmax(maxValue,CONVERT_COMPUTE_FLOAT4(vload4(0,input+offset+i*seq_len4)));\n"
" }\n"
" max_mnn[lid]=maxValue;\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" for (int i=SOFTMAX_LOCAL_SIZE/2; i>0; i /= 2) {\n"
" if (lid<i) {\n"
" max_mnn[lid]=fmax(max_mnn[lid],max_mnn[lid+i]);\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" }\n"
" maxValue=max_mnn[0];\n"
" COMPUTE_FLOAT4 sumValue=(COMPUTE_FLOAT4)0;\n"
" for (int i=lid; i<kv_seq_len; i += SOFTMAX_LOCAL_SIZE) {\n"
" sumValue += exp(CONVERT_COMPUTE_FLOAT4(vload4(0,input+offset+i*seq_len4))-maxValue);\n"
" }\n"
" sum_mnn[lid]=sumValue;\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" for (int i=SOFTMAX_LOCAL_SIZE/2; i>0; i /= 2) {\n"
" if (lid<i) {\n"
" sum_mnn[lid]=sum_mnn[lid]+sum_mnn[lid+i];\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" }\n"
" sumValue=sum_mnn[0];\n"
" for (int i=lid; i<kv_seq_len; i += SOFTMAX_LOCAL_SIZE) {\n"
" vstore4(CONVERT_FLOAT4(exp(CONVERT_COMPUTE_FLOAT4(vload4(0,input+offset+i*seq_len4))-maxValue)/sumValue),\n"
" 0,output+offset+i*seq_len4);\n"
" }\n"
"#else\n"
" COMPUTE_FLOAT4 maxValue=(COMPUTE_FLOAT4)-FLT_MAX;\n"
" for (int i=0; i<kv_seq_len; ++i) {\n"
" maxValue=fmax(maxValue,CONVERT_COMPUTE_FLOAT4(vload4(0,input+offset+i*seq_len4)));\n"
" }\n"
" COMPUTE_FLOAT4 sumValue=(COMPUTE_FLOAT4)0;\n"
" for (int i=0; i<kv_seq_len; ++i) {\n"
" sumValue += exp(CONVERT_COMPUTE_FLOAT4(vload4(0,input+offset+i*seq_len4))-maxValue);\n"
" }\n"
" for (int i=0; i<kv_seq_len; ++i) {\n"
" vstore4(CONVERT_FLOAT4(exp(CONVERT_COMPUTE_FLOAT4(vload4(0,input+offset+i*seq_len4))-maxValue)/sumValue),\n"
" 0,output+offset+i*seq_len4);\n"
" }\n"
"#endif\n"
"}\n"
"__kernel void matmul_qkv_prefill_packed(GLOBAL_SIZE_3_DIMS\n"
" __global const FLOAT *qk,// packed by request: [head_num kv_seq_len seq_len4]\n"
" __global const FLOAT *past_value,// packed by request: [kv_head_num max_len head_dim]\n"
" __global FLOAT *output,// [sum_seq_len head_num head_dim]\n"
" __global const int *meta0,\n"
" __global const int *meta1,\n"
" __global const int *meta2,\n"
" __private const int head_num,\n"
" __private const int kv_head_num,\n"
" __private const int head_dim) {\n"
" const int x=get_global_id(0); // head_dim/8\n"
" const int y=get_global_id(1); // query_seq_len/4\n"
" const int z=get_global_id(2); // req_count*head_num\n"
" DEAL_NON_UNIFORM_DIM3(x,y,z);\n"
" const int req=z/head_num;\n"
" const int hn=z % head_num;\n"
" const int io_offset=meta0[req*4+0];\n"
" const int seq_len=meta0[req*4+1];\n"
" const int max_len=meta0[req*4+3];\n"
" const int qk_base=meta1[req*4+1];\n"
" const int value_base=meta1[req*4+3];\n"
" const int kv_seq_len=meta2[req*4+2];\n"
" const int x8=x << 3;\n"
" const int y4=y << 2;\n"
" if (y4 >= seq_len) {\n"
" return;\n"
" }\n"
" const int seq_len4=(seq_len+3)/4*4;\n"
" const int qk_offset=qk_base+hn*kv_seq_len*seq_len4+y4;\n"
" const int past_offset=value_base+((hn/NUMHEAD_GROUP_SIZE)*max_len)*head_dim+x8;\n"
" const int loop_end=max(kv_seq_len/4-1,0);\n"
" COMPUTE_FLOAT8 out0=0,out1=0,out2=0,out3=0;\n"
" for (int i=0; i<loop_end; ++i) {\n"
" int i4=i << 2;\n"
" COMPUTE_FLOAT4 qk_vec0=CONVERT_COMPUTE_FLOAT4(vload4(0,qk+qk_offset+i4*seq_len4));\n"
" COMPUTE_FLOAT4 qk_vec1=CONVERT_COMPUTE_FLOAT4(vload4(0,qk+qk_offset+(i4+1)*seq_len4));\n"
" COMPUTE_FLOAT4 qk_vec2=CONVERT_COMPUTE_FLOAT4(vload4(0,qk+qk_offset+(i4+2)*seq_len4));\n"
" COMPUTE_FLOAT4 qk_vec3=CONVERT_COMPUTE_FLOAT4(vload4(0,qk+qk_offset+(i4+3)*seq_len4));\n"
" COMPUTE_FLOAT8 past_vec0=CONVERT_COMPUTE_FLOAT8(vload8(0,past_value+past_offset+i4*head_dim));\n"
" COMPUTE_FLOAT8 past_vec1=CONVERT_COMPUTE_FLOAT8(vload8(0,past_value+past_offset+(i4+1)*head_dim));\n"
" COMPUTE_FLOAT8 past_vec2=CONVERT_COMPUTE_FLOAT8(vload8(0,past_value+past_offset+(i4+2)*head_dim));\n"
" COMPUTE_FLOAT8 past_vec3=CONVERT_COMPUTE_FLOAT8(vload8(0,past_value+past_offset+(i4+3)*head_dim));\n"
" out0=mad((COMPUTE_FLOAT8)qk_vec0.s0,past_vec0,out0);\n"
" out0=mad((COMPUTE_FLOAT8)qk_vec1.s0,past_vec1,out0);\n"
" out0=mad((COMPUTE_FLOAT8)qk_vec2.s0,past_vec2,out0);\n"
" out0=mad((COMPUTE_FLOAT8)qk_vec3.s0,past_vec3,out0);\n"
" out1=mad((COMPUTE_FLOAT8)qk_vec0.s1,past_vec0,out1);\n"
" out1=mad((COMPUTE_FLOAT8)qk_vec1.s1,past_vec1,out1);\n"
" out1=mad((COMPUTE_FLOAT8)qk_vec2.s1,past_vec2,out1);\n"
" out1=mad((COMPUTE_FLOAT8)qk_vec3.s1,past_vec3,out1);\n"
" out2=mad((COMPUTE_FLOAT8)qk_vec0.s2,past_vec0,out2);\n"
" out2=mad((COMPUTE_FLOAT8)qk_vec1.s2,past_vec1,out2);\n"
" out2=mad((COMPUTE_FLOAT8)qk_vec2.s2,past_vec2,out2);\n"
" out2=mad((COMPUTE_FLOAT8)qk_vec3.s2,past_vec3,out2);\n"
" out3=mad((COMPUTE_FLOAT8)qk_vec0.s3,past_vec0,out3);\n"
" out3=mad((COMPUTE_FLOAT8)qk_vec1.s3,past_vec1,out3);\n"
" out3=mad((COMPUTE_FLOAT8)qk_vec2.s3,past_vec2,out3);\n"
" out3=mad((COMPUTE_FLOAT8)qk_vec3.s3,past_vec3,out3);\n"
" }\n"
" for (int i=(loop_end << 2); i<kv_seq_len; ++i) {\n"
" COMPUTE_FLOAT4 qk_vec=CONVERT_COMPUTE_FLOAT4(vload4(0,qk+qk_offset+i*seq_len4));\n"
" COMPUTE_FLOAT8 past_vec=CONVERT_COMPUTE_FLOAT8(vload8(0,past_value+past_offset+i*head_dim));\n"
" out0=mad((COMPUTE_FLOAT8)qk_vec.s0,past_vec,out0);\n"
" out1=mad((COMPUTE_FLOAT8)qk_vec.s1,past_vec,out1);\n"
" out2=mad((COMPUTE_FLOAT8)qk_vec.s2,past_vec,out2);\n"
" out3=mad((COMPUTE_FLOAT8)qk_vec.s3,past_vec,out3);\n"
" }\n"
" const int output_offset=((io_offset+y4)*head_num+hn)*head_dim+x8;\n"
" const int stride=head_num*head_dim;\n"
" vstore8(CONVERT_FLOAT8(out0),0,output+output_offset);\n"
" if (y4+1 >= seq_len) return;\n"
" vstore8(CONVERT_FLOAT8(out1),0,output+output_offset+stride);\n"
" if (y4+2 >= seq_len) return;\n"
" vstore8(CONVERT_FLOAT8(out2),0,output+output_offset+stride+stride);\n"
" if (y4+3 >= seq_len) return;\n"
" vstore8(CONVERT_FLOAT8(out3),0,output+output_offset+stride+stride+stride);\n"
"}\n"
"__kernel void matmul_qkv_decode_b8(GLOBAL_SIZE_2_DIMS\n"
" __global const FLOAT *qk,// qk [1 head_num qk_seq_len 1]\n"
" __global const FLOAT *past_value,// [1 head_num max_len head_dim]\n"
" __global FLOAT *output,// [1 1 head_num head_dim]\n"
" __private const int qk_seq_len,\n"
" __private const int max_len,\n"
" __private const int head_num,\n"
" __private const int kv_head_num,\n"
" __private const int head_dim) {\n"
" \n"
" const int x=get_global_id(0); // head_dim\n"
" const int y=get_global_id(1); // head_num\n"
" \n"
" DEAL_NON_UNIFORM_DIM2(x,y);\n"
" const int x8=x << 3;\n"
" \n"
" const int qk_offset=y*qk_seq_len;\n"
" const int past_offset=((y/NUMHEAD_GROUP_SIZE)*max_len)*head_dim+x8;\n"
" COMPUTE_FLOAT8 out0=0;\n"
" #ifdef LOOP_UNROLL_4\n"
" const int loop_end=max((qk_seq_len+3)/4-1,0);\n"
" for(int i=0; i<loop_end; ++i){\n"
" int i4=i << 2;\n"
" COMPUTE_FLOAT4 qk_vec=CONVERT_COMPUTE_FLOAT4(vload4(0,qk+qk_offset+i4));\n"
" \n"
" COMPUTE_FLOAT8 past_vec0=CONVERT_COMPUTE_FLOAT8(vload8(0,past_value+past_offset+i4*head_dim));\n"
" COMPUTE_FLOAT8 past_vec1=CONVERT_COMPUTE_FLOAT8(vload8(0,past_value+past_offset+(i4+1)*head_dim));\n"
" COMPUTE_FLOAT8 past_vec2=CONVERT_COMPUTE_FLOAT8(vload8(0,past_value+past_offset+(i4+2)*head_dim));\n"
" COMPUTE_FLOAT8 past_vec3=CONVERT_COMPUTE_FLOAT8(vload8(0,past_value+past_offset+(i4+3)*head_dim));\n"
" \n"
" out0=mad((COMPUTE_FLOAT8)qk_vec.s0,past_vec0,out0);\n"
" out0=mad((COMPUTE_FLOAT8)qk_vec.s1,past_vec1,out0);\n"
" out0=mad((COMPUTE_FLOAT8)qk_vec.s2,past_vec2,out0);\n"
" out0=mad((COMPUTE_FLOAT8)qk_vec.s3,past_vec3,out0);\n"
" }\n"
" for(int i=(loop_end << 2); i<qk_seq_len; ++i){\n"
" COMPUTE_FLOAT qk_vec=qk[qk_offset+i];\n"
" COMPUTE_FLOAT8 past_vec=CONVERT_COMPUTE_FLOAT8(vload8(0,past_value+past_offset+i*head_dim));\n"
" out0=mad((COMPUTE_FLOAT8)qk_vec,past_vec,out0);\n"
" }\n"
" #elif (defined LOOP_UNROLL_8)\n"
" const int loop_end=max((qk_seq_len+7)/8-1,0);\n"
" for(int i=0; i<loop_end; ++i){\n"
" int i8=i << 3;\n"
" COMPUTE_FLOAT8 qk_vec=CONVERT_COMPUTE_FLOAT8(vload8(0,qk+qk_offset+i8));\n"
" \n"
" COMPUTE_FLOAT8 past_vec0=CONVERT_COMPUTE_FLOAT8(vload8(0,past_value+past_offset+i8*head_dim));\n"
" COMPUTE_FLOAT8 past_vec1=CONVERT_COMPUTE_FLOAT8(vload8(0,past_value+past_offset+(i8+1)*head_dim));\n"
" COMPUTE_FLOAT8 past_vec2=CONVERT_COMPUTE_FLOAT8(vload8(0,past_value+past_offset+(i8+2)*head_dim));\n"
" COMPUTE_FLOAT8 past_vec3=CONVERT_COMPUTE_FLOAT8(vload8(0,past_value+past_offset+(i8+3)*head_dim));\n"
" COMPUTE_FLOAT8 past_vec4=CONVERT_COMPUTE_FLOAT8(vload8(0,past_value+past_offset+(i8+4)*head_dim));\n"
" COMPUTE_FLOAT8 past_vec5=CONVERT_COMPUTE_FLOAT8(vload8(0,past_value+past_offset+(i8+5)*head_dim));\n"
" COMPUTE_FLOAT8 past_vec6=CONVERT_COMPUTE_FLOAT8(vload8(0,past_value+past_offset+(i8+6)*head_dim));\n"
" COMPUTE_FLOAT8 past_vec7=CONVERT_COMPUTE_FLOAT8(vload8(0,past_value+past_offset+(i8+7)*head_dim));\n"
" \n"
" out0=mad((COMPUTE_FLOAT8)qk_vec.s0,past_vec0,out0);\n"
" out0=mad((COMPUTE_FLOAT8)qk_vec.s1,past_vec1,out0);\n"
" out0=mad((COMPUTE_FLOAT8)qk_vec.s2,past_vec2,out0);\n"
" out0=mad((COMPUTE_FLOAT8)qk_vec.s3,past_vec3,out0);\n"
" out0=mad((COMPUTE_FLOAT8)qk_vec.s4,past_vec4,out0);\n"
" out0=mad((COMPUTE_FLOAT8)qk_vec.s5,past_vec5,out0);\n"
" out0=mad((COMPUTE_FLOAT8)qk_vec.s6,past_vec6,out0);\n"
" out0=mad((COMPUTE_FLOAT8)qk_vec.s7,past_vec7,out0);\n"
" }\n"
" for(int i=(loop_end << 3); i<qk_seq_len; ++i){\n"
" COMPUTE_FLOAT qk_vec=qk[qk_offset+i];\n"
" COMPUTE_FLOAT8 past_vec=CONVERT_COMPUTE_FLOAT8(vload8(0,past_value+past_offset+i*head_dim));\n"
" out0=mad((COMPUTE_FLOAT8)qk_vec,past_vec,out0);\n"
" }\n"
" #endif\n"
" \n"
" const int output_offset=y*head_dim+x8;\n"
" vstore8(CONVERT_FLOAT8(out0),0,output+output_offset);\n"
"}\n"
"__kernel void matmul_qkv_decode_b8_packed(GLOBAL_SIZE_2_DIMS\n"
" __global const FLOAT *qk,\n"
" __global const FLOAT *past_value,\n"
" __global FLOAT *output,\n"
" __global const int *meta0,\n"
" __global const int *meta1,\n"
" __global const int *meta2,\n"
" __private const int head_num,\n"
" __private const int head_dim) {\n"
" const int x=get_global_id(0); // head_dim/8\n"
" const int z=get_global_id(1); // req_count*head_num\n"
" DEAL_NON_UNIFORM_DIM2(x,z);\n"
" const int req=z/head_num;\n"
" const int hn=z % head_num;\n"
" const int io_offset=meta0[req*4+0];\n"
" const int max_len=meta0[req*4+3];\n"
" const int qk_base=meta1[req*4+1];\n"
" const int value_base=meta1[req*4+3];\n"
" const int qk_seq_len=meta2[req*4+2];\n"
" const int x8=x << 3;\n"
" const int qk_offset=qk_base+hn*qk_seq_len;\n"
" const int past_offset=value_base+((hn/NUMHEAD_GROUP_SIZE)*max_len)*head_dim+x8;\n"
" COMPUTE_FLOAT8 out0=0;\n"
"#ifdef LOOP_UNROLL_4\n"
" const int loop_end=max((qk_seq_len+3)/4-1,0);\n"
" for (int i=0; i<loop_end; ++i) {\n"
" int i4=i << 2;\n"
" COMPUTE_FLOAT4 qk_vec=CONVERT_COMPUTE_FLOAT4(vload4(0,qk+qk_offset+i4));\n"
" COMPUTE_FLOAT8 past_vec0=CONVERT_COMPUTE_FLOAT8(vload8(0,past_value+past_offset+i4*head_dim));\n"
" COMPUTE_FLOAT8 past_vec1=CONVERT_COMPUTE_FLOAT8(vload8(0,past_value+past_offset+(i4+1)*head_dim));\n"
" COMPUTE_FLOAT8 past_vec2=CONVERT_COMPUTE_FLOAT8(vload8(0,past_value+past_offset+(i4+2)*head_dim));\n"
" COMPUTE_FLOAT8 past_vec3=CONVERT_COMPUTE_FLOAT8(vload8(0,past_value+past_offset+(i4+3)*head_dim));\n"
" out0=mad((COMPUTE_FLOAT8)qk_vec.s0,past_vec0,out0);\n"
" out0=mad((COMPUTE_FLOAT8)qk_vec.s1,past_vec1,out0);\n"
" out0=mad((COMPUTE_FLOAT8)qk_vec.s2,past_vec2,out0);\n"
" out0=mad((COMPUTE_FLOAT8)qk_vec.s3,past_vec3,out0);\n"
" }\n"
" for (int i=(loop_end << 2); i<qk_seq_len; ++i) {\n"
" COMPUTE_FLOAT qk_vec=qk[qk_offset+i];\n"
" COMPUTE_FLOAT8 past_vec=CONVERT_COMPUTE_FLOAT8(vload8(0,past_value+past_offset+i*head_dim));\n"
" out0=mad((COMPUTE_FLOAT8)qk_vec,past_vec,out0);\n"
" }\n"
"#endif\n"
" const int output_offset=(io_offset*head_num+hn)*head_dim+x8;\n"
" vstore8(CONVERT_FLOAT8(out0),0,output+output_offset);\n"
"}\n"
"__kernel void matmul_qkv_decode_b4(GLOBAL_SIZE_2_DIMS\n"
" __global const FLOAT *qk,// qk [1 head_num qk_seq_len 1]\n"
" __global const FLOAT *past_value,// [1 head_num max_len head_dim]\n"
" __global FLOAT *output,// [1 1 head_num head_dim]\n"
" __private const int qk_seq_len,\n"
" __private const int max_len,\n"
" __private const int head_num,\n"
" __private const int kv_head_num,\n"
" __private const int head_dim) {\n"
" \n"
" const int x=get_global_id(0); // head_dim\n"
" const int y=get_global_id(1); // head_num\n"
" \n"
" DEAL_NON_UNIFORM_DIM2(x,y);\n"
" const int x4=x << 2;\n"
" \n"
" const int qk_offset=y*qk_seq_len;\n"
" const int past_offset=((y/NUMHEAD_GROUP_SIZE)*max_len)*head_dim+x4;\n"
" COMPUTE_FLOAT4 out0=0;\n"
" #ifdef LOOP_UNROLL_4\n"
" const int loop_end=max((qk_seq_len+3)/4-1,0);\n"
" for(int i=0; i<loop_end; ++i){\n"
" int i4=i << 2;\n"
" COMPUTE_FLOAT4 qk_vec=CONVERT_COMPUTE_FLOAT4(vload4(0,qk+qk_offset+i4));\n"
" \n"
" COMPUTE_FLOAT4 past_vec0=CONVERT_COMPUTE_FLOAT4(vload4(0,past_value+past_offset+i4*head_dim));\n"
" COMPUTE_FLOAT4 past_vec1=CONVERT_COMPUTE_FLOAT4(vload4(0,past_value+past_offset+(i4+1)*head_dim));\n"
" COMPUTE_FLOAT4 past_vec2=CONVERT_COMPUTE_FLOAT4(vload4(0,past_value+past_offset+(i4+2)*head_dim));\n"
" COMPUTE_FLOAT4 past_vec3=CONVERT_COMPUTE_FLOAT4(vload4(0,past_value+past_offset+(i4+3)*head_dim));\n"
" \n"
" out0=mad((COMPUTE_FLOAT4)qk_vec.s0,past_vec0,out0);\n"
" out0=mad((COMPUTE_FLOAT4)qk_vec.s1,past_vec1,out0);\n"
" out0=mad((COMPUTE_FLOAT4)qk_vec.s2,past_vec2,out0);\n"
" out0=mad((COMPUTE_FLOAT4)qk_vec.s3,past_vec3,out0);\n"
" }\n"
" for(int i=(loop_end << 2); i<qk_seq_len; ++i){\n"
" COMPUTE_FLOAT qk_vec=qk[qk_offset+i];\n"
" COMPUTE_FLOAT4 past_vec=CONVERT_COMPUTE_FLOAT4(vload4(0,past_value+past_offset+i*head_dim));\n"
" out0=mad((COMPUTE_FLOAT4)qk_vec,past_vec,out0);\n"
" }\n"
" #elif (defined LOOP_UNROLL_8)\n"
" const int loop_end=max((qk_seq_len+7)/8-1,0);\n"
" for(int i=0; i<loop_end; ++i){\n"
" int i8=i << 3;\n"
" COMPUTE_FLOAT8 qk_vec=CONVERT_COMPUTE_FLOAT8(vload8(0,qk+qk_offset+i8));\n"
" \n"
" COMPUTE_FLOAT4 past_vec0=CONVERT_COMPUTE_FLOAT4(vload4(0,past_value+past_offset+i8*head_dim));\n"
" COMPUTE_FLOAT4 past_vec1=CONVERT_COMPUTE_FLOAT4(vload4(0,past_value+past_offset+(i8+1)*head_dim));\n"
" COMPUTE_FLOAT4 past_vec2=CONVERT_COMPUTE_FLOAT4(vload4(0,past_value+past_offset+(i8+2)*head_dim));\n"
" COMPUTE_FLOAT4 past_vec3=CONVERT_COMPUTE_FLOAT4(vload4(0,past_value+past_offset+(i8+3)*head_dim));\n"
" COMPUTE_FLOAT4 past_vec4=CONVERT_COMPUTE_FLOAT4(vload4(0,past_value+past_offset+(i8+4)*head_dim));\n"
" COMPUTE_FLOAT4 past_vec5=CONVERT_COMPUTE_FLOAT4(vload4(0,past_value+past_offset+(i8+5)*head_dim));\n"
" COMPUTE_FLOAT4 past_vec6=CONVERT_COMPUTE_FLOAT4(vload4(0,past_value+past_offset+(i8+6)*head_dim));\n"
" COMPUTE_FLOAT4 past_vec7=CONVERT_COMPUTE_FLOAT4(vload4(0,past_value+past_offset+(i8+7)*head_dim));\n"
" \n"
" out0=mad((COMPUTE_FLOAT4)qk_vec.s0,past_vec0,out0);\n"
" out0=mad((COMPUTE_FLOAT4)qk_vec.s1,past_vec1,out0);\n"
" out0=mad((COMPUTE_FLOAT4)qk_vec.s2,past_vec2,out0);\n"
" out0=mad((COMPUTE_FLOAT4)qk_vec.s3,past_vec3,out0);\n"
" out0=mad((COMPUTE_FLOAT4)qk_vec.s4,past_vec4,out0);\n"
" out0=mad((COMPUTE_FLOAT4)qk_vec.s5,past_vec5,out0);\n"
" out0=mad((COMPUTE_FLOAT4)qk_vec.s6,past_vec6,out0);\n"
" out0=mad((COMPUTE_FLOAT4)qk_vec.s7,past_vec7,out0);\n"
" }\n"
" for(int i=(loop_end << 3); i<qk_seq_len; ++i){\n"
" COMPUTE_FLOAT qk_vec=qk[qk_offset+i];\n"
" COMPUTE_FLOAT4 past_vec=CONVERT_COMPUTE_FLOAT4(vload4(0,past_value+past_offset+i*head_dim));\n"
" out0=mad((COMPUTE_FLOAT4)qk_vec,past_vec,out0);\n"
" }\n"
" #endif\n"
" \n"
" const int output_offset=y*head_dim+x4;\n"
" vstore4(CONVERT_FLOAT4(out0),0,output+output_offset);\n"
"}\n"
"// ---------------------------------------------------------------------------\n"
"// FlashAttention: Q*K^T -> online softmax -> P*V fused into one kernel. The\n"
"// S tile lives in local memory/registers and never reaches global memory,so\n"
"// nothing here scales with seqlen^2.\n"
"//\n"
"// Compile-time parameters,chosen in AttentionBufExecution::onResize from the\n"
"// measured device limits (CL_DEVICE_LOCAL_MEM_SIZE,CL_KERNEL_WORK_GROUP_SIZE,\n"
"// CL_KERNEL_PREFERRED_WORK_GROUP_SIZE_MULTIPLE):\n"
"// FA_HD head_dim,must be a multiple of FA_LSZ\n"
"// FA_TQ query rows per workgroup tile; multiple of 4,divides FA_LSZ\n"
"// FA_LSZ workgroup size,and also the KV rows per tile (Tkv == FA_LSZ)\n"
"// FA_DPT FA_HD/FA_LSZ,head-dim columns each thread owns during P*V\n"
"// FA_NLANE FA_LSZ/FA_TQ,threads cooperating on one row's reduction\n"
"// Optional: ADD_MASK/SET_MASK (same semantics as the other kernels here).\n"
"//\n"
"// Thread mapping\n"
"// phase 1 thread tid owns KV column tid and computes S[q][tid] for all q\n"
"// phase 2 threads regroup as (row,lane) for the cross-thread reductions\n"
"// phase 3 thread tid owns head-dim columns [tid*FA_DPT,tid*FA_DPT+FA_DPT)\n"
"//\n"
"// Precision: m,l and acc are fp32 (fp16 loses too much over thousands of\n"
"// accumulated terms). Q/K/V/P in local memory stay fp16,which is exactly the\n"
"// precision they already have in global memory,so nothing is lost there.\n"
"//\n"
"// Register pressure matters more than anything else here: every loop over q or\n"
"// d is fully unrolled and free of break/continue so that s[]/acc[] stay in\n"
"// registers. A data-dependent exit in those loops forces the arrays into\n"
"// private (scratch) memory and costs ~2x.\n"
"// ---------------------------------------------------------------------------\n"
"#ifndef FA_HD\n"
"#define FA_HD 128\n"
"#endif\n"
"#ifndef FA_TQ\n"
"#define FA_TQ 16\n"
"#endif\n"
"#ifndef FA_LSZ\n"
"#define FA_LSZ 64\n"
"#endif\n"
"#ifndef FA_DPT\n"
"#define FA_DPT (FA_HD/FA_LSZ)\n"
"#endif\n"
"#ifndef FA_NLANE\n"
"#define FA_NLANE (FA_LSZ/FA_TQ)\n"
"#endif\n"
"// FA_MIXED: multiply in fp16 and accumulate in fp16 for runs of FA_SEG terms,then flush\n"
"// into an fp32 running sum. Adreno runs half math at up to 2x the fp32 rate,and Q/K/V/P\n"
"// are already fp16 in memory,so the fp32 path was both converting on every load and giving\n"
"// up that rate. Error compounds only within a segment (FA_SEG terms) instead of across all\n"
"// head_dim*kv_seq_len terms,so this is far closer to fp32 than a fully fp16 accumulator.\n"
"// The online-softmax state (m,l,acc) stays fp32 regardless.\n"
"#ifndef FA_SEG\n"
"#define FA_SEG 16\n"
"#endif\n"
"// FA_SUBGROUP: do the cross-thread rowmax/rowsum with sub_group_reduce_* instead of the\n"
"// fp32 lS staging array. lS is the dominant local-memory consumer,and local footprint is\n"
"// what caps residency on this device,so removing it lets FA_TQ grow without losing\n"
"// occupancy. Requires cl_khr_subgroups (present on this Adreno) and FA_LSZ == subgroup size\n"
"// so that one workgroup is exactly one subgroup.\n"
"#define FA_NEG (-1e30f)\n"
"#define FA_QG (FA_TQ/4)\n"
"__kernel __attribute__((reqd_work_group_size(FA_LSZ,1,1)))\n"
"void flash_attention_prefill(\n"
" __global const FLOAT *query,// [batch,seq_len,head_num,head_dim]\n"
" __global const FLOAT *past_key,// [batch,kv_head_num,head_dim,max_len]\n"
" __global const FLOAT *past_value,// [batch,kv_head_num,max_len,head_dim]\n"
"#ifdef ADD_MASK\n"
" __global const FLOAT *mask,// [..,mask_q_len,mask_kv_len]\n"
"#elif defined(SET_MASK)\n"
" __global const int *mask,\n"
"#endif\n"
" __global FLOAT *output,// [batch,seq_len,head_num,head_dim]\n"
" __private const float scale,\n"
" __private const int seq_len,\n"
" __private const int kv_seq_len,\n"
" __private const int max_len,\n"
" __private const int mask_q_len,\n"
" __private const int mask_kv_len,\n"
" __private const int head_num,\n"
" __private const int kv_head_num,\n"
" __private const int q_tile_num,\n"
" __private const int bh_num,\n"
" __private const int causal_skip) {\n"
" const int tid=get_local_id(0);\n"
" const int qt=get_global_id(1); // query tile index\n"
" const int bh=get_global_id(2); // batch*head_num\n"
" if (qt >= q_tile_num || bh >= bh_num) {\n"
" return;\n"
" }\n"
" const int b=bh/head_num;\n"
" const int hn=bh % head_num;\n"
" const int kvh=hn/NUMHEAD_GROUP_SIZE;\n"
" const int q_start=qt*FA_TQ;\n"
" // fp16 for Q and P: same precision they already have in global memory,and\n"
" // halving the local footprint is what lets several workgroups stay resident\n"
" __local FLOAT lQ[FA_HD*FA_TQ]; // [d][q],so the q loop can vload4\n"
"#if defined(FA_SUBGROUP) && defined(FA_HALF_LS)\n"
" // On the subgroup path lS only ever holds P in [0,1],never the raw logits,so fp16 is\n"
" // safe here and halves the dominant local-memory consumer.\n"
" __local FLOAT lS[FA_LSZ*FA_TQ]; // [kv][q],kv-major for phase 3 vload4\n"
" #define FA_LS_LOAD4(ptr) convert_float4(vload4(0,(ptr)))\n"
" #define FA_LS_STORE(ptr,v) (*(ptr)=(FLOAT)(v))\n"
"#else\n"
" __local float lS[FA_LSZ*FA_TQ]; // [kv][q],kv-major for phase 3 vload4\n"
" #define FA_LS_LOAD4(ptr) vload4(0,(ptr))\n"
" #define FA_LS_STORE(ptr,v) (*(ptr)=(v))\n"
"#endif\n"
" __local float lRed[FA_TQ*FA_NLANE];\n"
" __local float lM[FA_TQ];\n"
" __local float lL[FA_TQ];\n"
" __local float lAlpha[FA_TQ];\n"
" // ---- load the Q tile verbatim (scale is applied to S instead,so this is\n"
" // an exact fp16 -> fp16 copy) ----\n"
" for (int i=tid; i<FA_HD*FA_TQ; i += FA_LSZ) {\n"
" const int q=i/FA_HD;\n"
" const int d=i-q*FA_HD; // consecutive tid -> consecutive d\n"
" const int gq=q_start+q;\n"
" lQ[d*FA_TQ+q]=(gq<seq_len) ? query[((b*seq_len+gq)*head_num+hn)*FA_HD+d] : (FLOAT)0;\n"
" }\n"
" if (tid<FA_TQ) {\n"
" lM[tid]=FA_NEG;\n"
" lL[tid]=0.0f;\n"
" }\n"
" float acc[FA_TQ][FA_DPT];\n"
" #pragma unroll\n"
" for (int q=0; q<FA_TQ; ++q) {\n"
" #pragma unroll\n"
" for (int d=0; d<FA_DPT; ++d) {\n"
" acc[q][d]=0.0f;\n"
" }\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" const int r_row=tid % FA_TQ; // consecutive tid -> consecutive\n"
" const int r_lane=tid/FA_TQ; // lS address,no bank conflict\n"
" const int d0=tid*FA_DPT;\n"
" // Causal bound. The mask maps kv -> kv+mask_kv_len-kv_seq_len and\n"
" // q -> q_start+ql,and everything whose mask-kv index exceeds its mask-q\n"
" // index is masked out,so a KV tile starting past the tile's last query row\n"
" // contributes nothing and can be skipped outright. That is ~half the QK\n"
" // FLOPs at long prompts.\n"
" const int kv_limit=causal_skip\n"
" ? min(kv_seq_len,q_start+FA_TQ+kv_seq_len-mask_kv_len)\n"
" : kv_seq_len;\n"
" const int koff=(b*kv_head_num+kvh)*FA_HD*max_len+tid;\n"
" const int voff=(b*kv_head_num+kvh)*max_len*FA_HD+d0;\n"
" for (int kv_base=0; kv_base<kv_limit; kv_base += FA_LSZ) {\n"
" const int kv=kv_base+tid;\n"
" const int kv_ok=(kv<kv_seq_len);\n"
" // ---- phase 1: S[q][tid]=sum_d Q[q][d]*K[d][kv] ----\n"
" float s[FA_TQ];\n"
" #pragma unroll\n"
" for (int q=0; q<FA_TQ; ++q) {\n"
" s[q]=0.0f;\n"
" }\n"
" if (kv_ok) {\n"
" const int kbase=koff+kv_base;\n"
"#ifdef FA_MIXED\n"
" // past_key and lQ are both already fp16,so this loop does no conversions at\n"
" // all in the inner body-only one convert per FA_SEG terms at the flush.\n"
" float4 sacc[FA_QG];\n"
" #pragma unroll\n"
" for (int g=0; g<FA_QG; ++g) {\n"
" sacc[g]=(float4)0.0f;\n"
" }\n"
" for (int dseg=0; dseg<FA_HD; dseg += FA_SEG) {\n"
" half4 hacc[FA_QG];\n"
" #pragma unroll\n"
" for (int g=0; g<FA_QG; ++g) {\n"
" hacc[g]=(half4)0.0h;\n"
" }\n"
" #pragma unroll\n"
" for (int dd=0; dd<FA_SEG; ++dd) {\n"
" const int d=dseg+dd;\n"
" const half4 kval=(half4)((half)past_key[kbase+d*max_len]);\n"
" #pragma unroll\n"
" for (int g=0; g<FA_QG; ++g) {\n"
" hacc[g]=mad(kval,vload4(0,lQ+d*FA_TQ+g*4),hacc[g]);\n"
" }\n"
" }\n"
" #pragma unroll\n"
" for (int g=0; g<FA_QG; ++g) {\n"
" sacc[g] += convert_float4(hacc[g]);\n"
" }\n"
" }\n"
" #pragma unroll\n"
" for (int g=0; g<FA_QG; ++g) {\n"
" s[g*4+0]=sacc[g].s0;\n"
" s[g*4+1]=sacc[g].s1;\n"
" s[g*4+2]=sacc[g].s2;\n"
" s[g*4+3]=sacc[g].s3;\n"
" }\n"
"#else\n"
" for (int d=0; d<FA_HD; ++d) {\n"
" const float kval=(float)past_key[kbase+d*max_len];\n"
" #pragma unroll\n"
" for (int q=0; q<FA_TQ; q += 4) {\n"
" const float4 qv=convert_float4(vload4(0,lQ+d*FA_TQ+q));\n"
" s[q+0]=mad(kval,qv.s0,s[q+0]);\n"
" s[q+1]=mad(kval,qv.s1,s[q+1]);\n"
" s[q+2]=mad(kval,qv.s2,s[q+2]);\n"
" s[q+3]=mad(kval,qv.s3,s[q+3]);\n"
" }\n"
" }\n"
"#endif\n"
" }\n"
" // ---- mask,then publish S so the row max can be reduced across threads.\n"
" // No break/continue here: that would stop the unroll and push s[]\n"
" // into scratch memory.\n"
" {\n"
" const int mk=kv+mask_kv_len-kv_seq_len;\n"
" const int mk_ok=kv_ok && (mk >= 0) && (mk<mask_kv_len);\n"
" #pragma unroll\n"
" for (int q=0; q<FA_TQ; ++q) {\n"
" const int gq=q_start+q;\n"
" float v=s[q]*scale;\n"
"#if defined(ADD_MASK)\n"
" const float mv=(mk_ok && gq<mask_q_len) ? (float)mask[gq*mask_kv_len+mk] : 0.0f;\n"
" v=fmax(v+mv,FA_NEG);\n"
"#elif defined(SET_MASK)\n"
" const int mvi=(mk_ok && gq<mask_q_len) ? mask[gq*mask_kv_len+mk] : 0;\n"
" v=(mvi == 0) ? FA_NEG : v;\n"
"#endif\n"
" v=(kv_ok && gq<seq_len) ? v : FA_NEG;\n"
" s[q]=v;\n"
"#ifndef FA_SUBGROUP\n"
" lS[tid*FA_TQ+q]=v;\n"
"#endif\n"
" }\n"
" }\n"
"#ifndef FA_SUBGROUP\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
"#endif\n"
" // ---- phase 2a: running max and the rescale factor alpha ----\n"
"#ifdef FA_SUBGROUP\n"
" // One reduction per query row across the whole subgroup; no local staging.\n"
" #pragma unroll\n"
" for (int q=0; q<FA_TQ; ++q) {\n"
" const float tmax=sub_group_reduce_max(s[q]);\n"
" if (tid == 0) {\n"
" const float m_prev=lM[q];\n"
" const float m_new=fmax(m_prev,tmax);\n"
" lAlpha[q]=native_exp(m_prev-m_new);\n"
" lM[q]=m_new;\n"
" }\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
"#else\n"
" {\n"
" float pmax=FA_NEG;\n"
" const int kend=(r_lane+1)*FA_TQ;\n"
" for (int k=r_lane*FA_TQ; k<kend; ++k) {\n"
" pmax=fmax(pmax,lS[k*FA_TQ+r_row]);\n"
" }\n"
" lRed[r_lane*FA_TQ+r_row]=pmax;\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" if (tid<FA_TQ) {\n"
" float tmax=lRed[tid];\n"
" #pragma unroll\n"
" for (int l=1; l<FA_NLANE; ++l) {\n"
" tmax=fmax(tmax,lRed[l*FA_TQ+tid]);\n"
" }\n"
" const float m_prev=lM[tid];\n"
" const float m_new=fmax(m_prev,tmax);\n"
" // both operands are finite (S is clamped to FA_NEG),so this can\n"
" // never produce inf-inf\n"
" lAlpha[tid]=native_exp(m_prev-m_new);\n"
" lM[tid]=m_new;\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
"#endif\n"
" // ---- phase 2b: P=exp(S-m_new),straight from registers ----\n"
"#ifdef FA_SUBGROUP\n"
" // one pass: compute P,publish it,and reduce its row sum in the same loop\n"
" #pragma unroll\n"
" for (int q=0; q<FA_TQ; ++q) {\n"
" const float sv=s[q];\n"
" const float pq=(sv <= FA_NEG) ? 0.0f : native_exp(sv-lM[q]);\n"
" FA_LS_STORE(lS+tid*FA_TQ+q,pq);\n"
" const float tsum=sub_group_reduce_add(pq);\n"
" if (tid == 0) {\n"
" lL[q]=lL[q]*lAlpha[q]+tsum;\n"
" }\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
"#else\n"
" #pragma unroll\n"
" for (int q=0; q<FA_TQ; ++q) {\n"
" const float sv=s[q];\n"
" lS[tid*FA_TQ+q]=(sv <= FA_NEG) ? 0.0f : native_exp(sv-lM[q]);\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" {\n"
" float psum=0.0f;\n"
" const int kend=(r_lane+1)*FA_TQ;\n"
" for (int k=r_lane*FA_TQ; k<kend; ++k) {\n"
" psum += lS[k*FA_TQ+r_row];\n"
" }\n"
" lRed[r_lane*FA_TQ+r_row]=psum;\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" if (tid<FA_TQ) {\n"
" float tsum=lRed[tid];\n"
" #pragma unroll\n"
" for (int l=1; l<FA_NLANE; ++l) {\n"
" tsum += lRed[l*FA_TQ+tid];\n"
" }\n"
" lL[tid]=lL[tid]*lAlpha[tid]+tsum;\n"
" }\n"
"#endif\n"
" // ---- phase 3: acc=acc*alpha+P*V ----\n"
" #pragma unroll\n"
" for (int q=0; q<FA_TQ; ++q) {\n"
" const float a=lAlpha[q];\n"
" #pragma unroll\n"
" for (int d=0; d<FA_DPT; ++d) {\n"
" acc[q][d] *= a;\n"
" }\n"
" }\n"
" {\n"
" const int kend=min(FA_LSZ,kv_seq_len-kv_base);\n"
"#ifdef FA_MIXED\n"
" // Same segmenting over the KV dimension. acc itself stays fp32 across tiles -\n"
" // it is the online-softmax state and sees thousands of terms.\n"
" for (int kseg=0; kseg<kend; kseg += FA_SEG) {\n"
" const int kstop=min(kseg+FA_SEG,kend);\n"
" half4 hacc[FA_QG][FA_DPT];\n"
" #pragma unroll\n"
" for (int g=0; g<FA_QG; ++g) {\n"
" #pragma unroll\n"
" for (int d=0; d<FA_DPT; ++d) {\n"
" hacc[g][d]=(half4)0.0h;\n"
" }\n"
" }\n"
" for (int k=kseg; k<kstop; ++k) {\n"
" half vv[FA_DPT];\n"
" #pragma unroll\n"
" for (int d=0; d<FA_DPT; ++d) {\n"
" vv[d]=(half)past_value[voff+(kv_base+k)*FA_HD+d];\n"
" }\n"
" #pragma unroll\n"
" for (int g=0; g<FA_QG; ++g) {\n"
" const half4 pv=convert_half4(FA_LS_LOAD4(lS+k*FA_TQ+g*4));\n"
" #pragma unroll\n"
" for (int d=0; d<FA_DPT; ++d) {\n"
" hacc[g][d]=mad(pv,(half4)vv[d],hacc[g][d]);\n"
" }\n"
" }\n"
" }\n"
" #pragma unroll\n"
" for (int g=0; g<FA_QG; ++g) {\n"
" #pragma unroll\n"
" for (int d=0; d<FA_DPT; ++d) {\n"
" const float4 f=convert_float4(hacc[g][d]);\n"
" acc[g*4+0][d] += f.s0;\n"
" acc[g*4+1][d] += f.s1;\n"
" acc[g*4+2][d] += f.s2;\n"
" acc[g*4+3][d] += f.s3;\n"
" }\n"
" }\n"
" }\n"
"#else\n"
" for (int k=0; k<kend; ++k) {\n"
" float vv[FA_DPT];\n"
" #pragma unroll\n"
" for (int d=0; d<FA_DPT; ++d) {\n"
" vv[d]=(float)past_value[voff+(kv_base+k)*FA_HD+d];\n"
" }\n"
" #pragma unroll\n"
" for (int q=0; q<FA_TQ; q += 4) {\n"
" const float4 pv=FA_LS_LOAD4(lS+k*FA_TQ+q);\n"
" #pragma unroll\n"
" for (int d=0; d<FA_DPT; ++d) {\n"
" acc[q+0][d]=mad(pv.s0,vv[d],acc[q+0][d]);\n"
" acc[q+1][d]=mad(pv.s1,vv[d],acc[q+1][d]);\n"
" acc[q+2][d]=mad(pv.s2,vv[d],acc[q+2][d]);\n"
" acc[q+3][d]=mad(pv.s3,vv[d],acc[q+3][d]);\n"
" }\n"
" }\n"
" }\n"
"#endif\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" }\n"
" // ---- epilogue: out=acc/l. Predicated store,not an early break,so the\n"
" // loop still unrolls and acc[] stays in registers.\n"
" #pragma unroll\n"
" for (int q=0; q<FA_TQ; ++q) {\n"
" const int gq=q_start+q;\n"
" const float lsum=lL[q];\n"
" const float inv=(lsum>0.0f) ? (1.0f/lsum) : 0.0f;\n"
" if (gq<seq_len) {\n"
" const int ooff=((b*seq_len+gq)*head_num+hn)*FA_HD+d0;\n"
" #pragma unroll\n"
" for (int d=0; d<FA_DPT; ++d) {\n"
" output[ooff+d]=(FLOAT)(acc[q][d]*inv);\n"
" }\n"
" }\n"
" }\n"
"}\n"
;
#endif
}
