#include "opencl_source_map.hpp" 
namespace MNN { 
#ifndef MNN_OPENCL_BUFFER_CLOSED
const char* softmax_buf = 
"#ifdef MNN_SUPPORT_FP16\n"
"#pragma OPENCL EXTENSION cl_khr_fp16 : enable\n"
"#endif\n"
"#define EXP exp\n"
"#define GLOBAL_SIZE_3_DIMS "" __private const int global_size_dim0,__private const int global_size_dim1,__private const int global_size_dim2,\n"
"#define DEAL_NON_UNIFORM_DIM3(input1, input2, input3) "" if (input1 >= global_size_dim0 || input2 >= global_size_dim1 || input3 >= global_size_dim2) { "" return; "" }\n"
"__kernel void softmax_in1_buf(GLOBAL_SIZE_3_DIMS\n"
" __global const FLOAT *input,\n"
" __global FLOAT *output,\n"
" __private const int inside,\n"
" __private const int outside,\n"
" __private const int dim) {\n"
" const int x=get_global_id(0);\n"
" const int y=get_global_id(1); // inside=1\n"
" const int z=get_global_id(2); // outside\n"
" DEAL_NON_UNIFORM_DIM3(x,y,z);\n"
" \n"
" const int offset=z*dim+y;\n"
" const int dim4=(dim+3)/4;\n"
" const int loop_end=max(0,dim4-1);\n"
"#if SOFTMAX_LOCAL_SIZE >= 4\n"
" int lid=get_local_id(0);\n"
" COMPUTE_FLOAT local sum_mnn[SOFTMAX_LOCAL_SIZE];\n"
" COMPUTE_FLOAT local max_mnn[SOFTMAX_LOCAL_SIZE];\n"
" // compute maxvalue\n"
" COMPUTE_FLOAT4 maxValue=(COMPUTE_FLOAT4)-FLT_MAX;\n"
" for (int i=lid; i<loop_end; i+=SOFTMAX_LOCAL_SIZE) {\n"
" maxValue=fmax(maxValue,CONVERT_COMPUTE_FLOAT4(vload4(i,input+offset)));\n"
" }\n"
" max_mnn[lid]=fmax(fmax(fmax(maxValue.x,maxValue.y),maxValue.z),maxValue.w);\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" for(int i=SOFTMAX_LOCAL_SIZE/2; i>0; i /= 2){\n"
" if (lid<i)\n"
" max_mnn[lid]=fmax(max_mnn[lid],max_mnn[lid+i]);\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" }\n"
" maxValue.x=max_mnn[0];\n"
" for(int i=loop_end << 2; i<dim; ++i){\n"
" maxValue.x=fmax(maxValue.x,(COMPUTE_FLOAT)(input[offset+i]));\n"
" }\n"
" // compute sumvalue\n"
" COMPUTE_FLOAT4 sumValue=(COMPUTE_FLOAT4)0;\n"
" for (int i=lid; i<loop_end; i+=SOFTMAX_LOCAL_SIZE) {\n"
" sumValue += exp(CONVERT_COMPUTE_FLOAT4(vload4(i,input+offset))-(COMPUTE_FLOAT4)maxValue.x);\n"
" }\n"
" sum_mnn[lid]=sumValue.x+sumValue.y+sumValue.z+sumValue.w;\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" for(int i=SOFTMAX_LOCAL_SIZE/2; i>0; i /= 2){\n"
" if (lid<i)\n"
" sum_mnn[lid]=sum_mnn[lid]+sum_mnn[lid+i];\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" }\n"
" sumValue.x=sum_mnn[0];\n"
" for(int i=loop_end << 2; i<dim; ++i){\n"
" sumValue.x += exp((COMPUTE_FLOAT)(input[offset+i])-maxValue.x);\n"
" }\n"
" \n"
" // store result\n"
" for(int i=lid; i<loop_end; i+=SOFTMAX_LOCAL_SIZE){\n"
" vstore4(CONVERT_FLOAT4(exp(CONVERT_COMPUTE_FLOAT4(vload4(i,input+offset))-(COMPUTE_FLOAT4)maxValue.x)/(COMPUTE_FLOAT4)sumValue.x),0,output+offset+i*4);\n"
" }\n"
" for(int i=loop_end << 2; i<dim; ++i){\n"
" output[offset+i]=(FLOAT)exp((COMPUTE_FLOAT)(input[offset+i])-maxValue.x)/sumValue.x;\n"
" }\n"
"#else\n"
" // compute maxvalue\n"
" COMPUTE_FLOAT4 maxValue=(COMPUTE_FLOAT4)-FLT_MAX;\n"
" for (int i=0; i<loop_end; i++) {\n"
" maxValue=fmax(maxValue,CONVERT_COMPUTE_FLOAT4(vload4(i,input+offset)));\n"
" }\n"
" maxValue.x=fmax(fmax(fmax(maxValue.x,maxValue.y),maxValue.z),maxValue.w);\n"
" for(int i=loop_end << 2; i<dim; ++i){\n"
" maxValue.x=fmax(maxValue.x,(COMPUTE_FLOAT)(input[offset+i]));\n"
" }\n"
" \n"
" // compute sumvalue\n"
" COMPUTE_FLOAT4 sumValue=(COMPUTE_FLOAT4)0;\n"
" for (int i=0; i<loop_end; i++) {\n"
" sumValue += exp(CONVERT_COMPUTE_FLOAT4(vload4(i,input+offset))-(COMPUTE_FLOAT4)maxValue.x);\n"
" }\n"
" sumValue.x=sumValue.x+sumValue.y+sumValue.z+sumValue.w;\n"
" for(int i=loop_end << 2; i<dim; ++i){\n"
" sumValue.x += exp((COMPUTE_FLOAT)(input[offset+i])-maxValue.x);\n"
" }\n"
" \n"
" // store result\n"
" for(int i=0; i<loop_end; i++){\n"
" vstore4(CONVERT_FLOAT4(exp(CONVERT_COMPUTE_FLOAT4(vload4(i,input+offset))-(COMPUTE_FLOAT4)maxValue.x)/(COMPUTE_FLOAT4)sumValue.x),0,output+offset+i*4);\n"
" }\n"
" for(int i=loop_end << 2; i<dim; ++i){\n"
" output[offset+i]=(FLOAT)exp((COMPUTE_FLOAT)(input[offset+i])-maxValue.x)/sumValue.x;\n"
" }\n"
"#endif\n"
"}\n"
"__kernel void softmax_buf(GLOBAL_SIZE_3_DIMS\n"
" __global const FLOAT *input,\n"
" __global FLOAT *output,\n"
" __private const int inside,\n"
" __private const int outside,\n"
" __private const int dim) {\n"
" const int x=get_global_id(0);\n"
" const int y=get_global_id(1); // inside\n"
" const int z=get_global_id(2); // outside\n"
" DEAL_NON_UNIFORM_DIM3(x,y,z);\n"
" \n"
" const int offset=z*dim*inside+y;\n"
"#if SOFTMAX_LOCAL_SIZE >= 4\n"
" int lid=get_local_id(0);\n"
" COMPUTE_FLOAT local sum_mnn[SOFTMAX_LOCAL_SIZE];\n"
" COMPUTE_FLOAT local max_mnn[SOFTMAX_LOCAL_SIZE];\n"
" COMPUTE_FLOAT maxValue=(COMPUTE_FLOAT)-FLT_MAX;\n"
" for (int i=lid; i<dim; i+=SOFTMAX_LOCAL_SIZE) {\n"
" maxValue=fmax(maxValue,(COMPUTE_FLOAT)(input[offset+i*inside]));\n"
" }\n"
" max_mnn[lid]=maxValue;\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" for(int i=SOFTMAX_LOCAL_SIZE/2; i>0; i /= 2){\n"
" if (lid<i)\n"
" max_mnn[lid]=fmax(max_mnn[lid],max_mnn[lid+i]);\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" }\n"
" maxValue=max_mnn[0];\n"
" COMPUTE_FLOAT sumValue=(COMPUTE_FLOAT)0;\n"
" for (int i=lid; i<dim; i+=SOFTMAX_LOCAL_SIZE) {\n"
" sumValue += exp((COMPUTE_FLOAT)(input[offset+i*inside])-maxValue);\n"
" }\n"
" sum_mnn[lid]=sumValue;\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" for(int i=SOFTMAX_LOCAL_SIZE/2; i>0; i /= 2){\n"
" if (lid<i)\n"
" sum_mnn[lid]=sum_mnn[lid]+sum_mnn[lid+i];\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" }\n"
" sumValue=sum_mnn[0];\n"
" for(int i=lid; i<dim; i+=SOFTMAX_LOCAL_SIZE){\n"
" output[offset+i*inside]=(FLOAT)exp((COMPUTE_FLOAT)(input[offset+i*inside])-maxValue)/sumValue;\n"
" }\n"
"#else\n"
" COMPUTE_FLOAT maxValue=(COMPUTE_FLOAT)-FLT_MAX;\n"
" for (int i=0; i<dim; i++) {\n"
" maxValue=fmax(maxValue,(COMPUTE_FLOAT)(input[offset+i*inside]));\n"
" }\n"
" COMPUTE_FLOAT sumValue=(COMPUTE_FLOAT)0;\n"
" for (int i=0; i<dim; i++) {\n"
" sumValue += exp((COMPUTE_FLOAT)(input[offset+i*inside])-maxValue);\n"
" }\n"
" for(int i=0; i<dim; i++){\n"
" output[offset+i*inside]=(FLOAT)exp((COMPUTE_FLOAT)(input[offset+i*inside])-maxValue)/sumValue;\n"
" }\n"
"#endif\n"
"}\n"
"__kernel void softmax_v4_buf(GLOBAL_SIZE_3_DIMS\n"
" __global const FLOAT *input,\n"
" __global FLOAT *output,\n"
" __private const int inside,\n"
" __private const int outside,\n"
" __private const int dim) {\n"
" const int x=get_global_id(0);\n"
" const int y=get_global_id(1); // inside\n"
" const int z=get_global_id(2); // outside\n"
" DEAL_NON_UNIFORM_DIM3(x,y,z);\n"
" \n"
" const int offset=z*dim*inside+(y << 2);\n"
"#if SOFTMAX_LOCAL_SIZE >= 4\n"
" int lid=get_local_id(0);\n"
" COMPUTE_FLOAT4 local sum_mnn[SOFTMAX_LOCAL_SIZE];\n"
" COMPUTE_FLOAT4 local max_mnn[SOFTMAX_LOCAL_SIZE];\n"
" COMPUTE_FLOAT4 maxValue=(COMPUTE_FLOAT4)-FLT_MAX;\n"
" for (int i=lid; i<dim; i+=SOFTMAX_LOCAL_SIZE) {\n"
" maxValue=fmax(maxValue,CONVERT_COMPUTE_FLOAT4(vload4(0,input+offset+i*inside)));\n"
" }\n"
" max_mnn[lid]=maxValue;\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" for(int i=SOFTMAX_LOCAL_SIZE/2; i>0; i /= 2){\n"
" if (lid<i)\n"
" max_mnn[lid]=fmax(max_mnn[lid],max_mnn[lid+i]);\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" }\n"
" maxValue=max_mnn[0];\n"
" COMPUTE_FLOAT4 sumValue=(COMPUTE_FLOAT4)0;\n"
" for (int i=lid; i<dim; i+=SOFTMAX_LOCAL_SIZE) {\n"
" sumValue += exp(CONVERT_COMPUTE_FLOAT4(vload4(0,input+offset+i*inside))-maxValue);\n"
" }\n"
" sum_mnn[lid]=sumValue;\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" for(int i=SOFTMAX_LOCAL_SIZE/2; i>0; i /= 2){\n"
" if (lid<i)\n"
" sum_mnn[lid]=sum_mnn[lid]+sum_mnn[lid+i];\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" }\n"
" sumValue=sum_mnn[0];\n"
" for(int i=lid; i<dim; i+=SOFTMAX_LOCAL_SIZE){\n"
" vstore4(CONVERT_FLOAT4(exp(CONVERT_COMPUTE_FLOAT4(vload4(0,input+offset+i*inside))-maxValue)/sumValue),0,output+offset+i*inside);\n"
" }\n"
"#else\n"
" COMPUTE_FLOAT4 maxValue=(COMPUTE_FLOAT4)-FLT_MAX;\n"
" for (int i=0; i<dim; i++) {\n"
" maxValue=fmax(maxValue,CONVERT_COMPUTE_FLOAT4(vload4(0,input+offset+i*inside)));\n"
" }\n"
" COMPUTE_FLOAT4 sumValue=(COMPUTE_FLOAT4)0;\n"
" for (int i=0; i<dim; i++) {\n"
" sumValue += exp(CONVERT_COMPUTE_FLOAT4(vload4(0,input+offset+i*inside))-maxValue);\n"
" }\n"
" for(int i=0; i<dim; i++){\n"
" vstore4(CONVERT_FLOAT4(exp(CONVERT_COMPUTE_FLOAT4(vload4(0,input+offset+i*inside))-maxValue)/sumValue),0,output+offset+i*inside);\n"
" }\n"
"#endif\n"
"}\n"
"// ---------------------------------------------------------------------------\n"
"// Online (single-pass statistics) variant of softmax_v4_buf.\n"
"//\n"
"// Baseline reads the reduction axis 3x (max/expsum/write). This variant\n"
"// keeps a running (m,l) pair so the max and the exp-sum are produced in ONE\n"
"// traversal: m'=max(m,x),l'=l*exp(m-m')+exp(x-m')\n"
"// The pair merge is associative,so per-thread partials combine with the same\n"
"// tree reduction shape the baseline uses. A second traversal writes\n"
"// exp(x-m)/l,so the kernel is 2 reads+1 write instead of 3 reads+1 write.\n"
"//\n"
"// Accumulators are float4 (not COMPUTE_FLOAT4): at precision low\n"
"// COMPUTE_FLOAT is half,and l is summed over thousands of terms.\n"
"// ---------------------------------------------------------------------------\n"
"__kernel void softmax_v4_online_buf(GLOBAL_SIZE_3_DIMS\n"
" __global const FLOAT *input,\n"
" __global FLOAT *output,\n"
" __private const int inside,\n"
" __private const int outside,\n"
" __private const int dim) {\n"
" const int x=get_global_id(0);\n"
" const int y=get_global_id(1); // inside\n"
" const int z=get_global_id(2); // outside\n"
" DEAL_NON_UNIFORM_DIM3(x,y,z);\n"
" const int offset=z*dim*inside+(y << 2);\n"
"#if SOFTMAX_LOCAL_SIZE >= 4\n"
" int lid=get_local_id(0);\n"
" float4 local sum_mnn[SOFTMAX_LOCAL_SIZE];\n"
" float4 local max_mnn[SOFTMAX_LOCAL_SIZE];\n"
" /* Pass 1: running max+running sum,single traversal */\n"
" float4 runMax=(float4)(-FLT_MAX);\n"
" float4 runSum=(float4)0;\n"
" for (int i=lid; i<dim; i+=SOFTMAX_LOCAL_SIZE) {\n"
" float4 v=convert_float4(vload4(0,input+offset+i*inside));\n"
" if (any(isgreater(v,runMax))) {\n"
" float4 m=fmax(runMax,v);\n"
" runSum=runSum*exp(runMax-m)+exp(v-m);\n"
" runMax=m;\n"
" } else {\n"
" runSum += exp(v-runMax);\n"
" }\n"
" }\n"
" max_mnn[lid]=runMax;\n"
" sum_mnn[lid]=runSum;\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" /* associative (m,l) pair merge */\n"
" for(int i=SOFTMAX_LOCAL_SIZE/2; i>0; i /= 2){\n"
" if (lid<i) {\n"
" float4 mA=max_mnn[lid],lA=sum_mnn[lid];\n"
" float4 mB=max_mnn[lid+i],lB=sum_mnn[lid+i];\n"
" float4 m=fmax(mA,mB);\n"
" max_mnn[lid]=m;\n"
" sum_mnn[lid]=lA*exp(mA-m)+lB*exp(mB-m);\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" }\n"
" float4 maxValue=max_mnn[0];\n"
" float4 sumValue=sum_mnn[0];\n"
" /* Pass 2: write out */\n"
" for(int i=lid; i<dim; i+=SOFTMAX_LOCAL_SIZE){\n"
" vstore4(CONVERT_FLOAT4(exp(convert_float4(vload4(0,input+offset+i*inside))-maxValue)/sumValue),0,output+offset+i*inside);\n"
" }\n"
"#else\n"
" float4 maxValue=(float4)(-FLT_MAX);\n"
" float4 sumValue=(float4)0;\n"
" for (int i=0; i<dim; i++) {\n"
" float4 v=convert_float4(vload4(0,input+offset+i*inside));\n"
" if (any(isgreater(v,maxValue))) {\n"
" float4 m=fmax(maxValue,v);\n"
" sumValue=sumValue*exp(maxValue-m)+exp(v-m);\n"
" maxValue=m;\n"
" } else {\n"
" sumValue += exp(v-maxValue);\n"
" }\n"
" }\n"
" for(int i=0; i<dim; i++){\n"
" vstore4(CONVERT_FLOAT4(exp(convert_float4(vload4(0,input+offset+i*inside))-maxValue)/sumValue),0,output+offset+i*inside);\n"
" }\n"
"#endif\n"
"}\n"
;
#endif
}
